CREATE TABLE LOGIN_HISTORY (	
	 SEQ numeric  NOT NULL 
	, USER_ID varchar(30)  NOT NULL 
	, USER_IP varchar(50) 
	, USER_AGENT varchar(200) 
	, LOGIN_DATE timestamp  ); 

CREATE TABLE TB_ACCESS_LOG (	
	  MENU_ID varchar(100) 
	, USER_ID varchar(30) 
	, REFERER varchar(500) 
	, USER_IP varchar(20) 
	, USER_AGENT varchar(200) 
	, ACCESS_DATE timestamp  ); 

CREATE TABLE TB_ADMIN_USER (	
	  USER_ID varchar(30)  NOT NULL 
	, "PASSWORD" varchar(50)  NOT NULL 
	, "NAME" varchar(50) 
	, EN_"NAME" varchar(50) 
	, "TYPE" varchar(10) 
	, USE_YN char(1) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 




CREATE TABLE TB_APT_INFO (	
	  SEQ numeric  NOT NULL 
	, GAME_SEQ numeric  NOT NULL 
	, FIRST_APT_MIN numeric 
	, FIRST_APT_SEC numeric 
	, SECOND_APT_MIN numeric 
	, SECOND_APT_SEC numeric 
	, TOTAL_APT_MIN numeric 
	, TOTAL_APT_SEC numeric 
	, REG_USER varchar(50) 
	, REG_DATE timestamp  ); 

CREATE TABLE TB_ASSIGN_STOP (	
	  SEQ numeric  NOT NULL 
	, GAME_SEQ numeric  NOT NULL 
	, GAME_HISTORY_SEQ numeric  NOT NULL 
	, GAME_HISTORY_WRONG_SEQ numeric  NOT NULL 
	, ADVANTAGE_TEAM varchar(10) 
	, DISADVANTAGE_TEAM varchar(10) 
	, EFFECT_YN char(1) 
	, STOP_DAY varchar(10) 
	, NOTE varchar(100) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_ATTACH_FILE (	
	  SEQ numeric  NOT NULL 
	, GROUP_SEQ numeric  NOT NULL 
	, FILE_PATH varchar(100) 
	, FILE_"NAME" varchar(100) 
	, ORIGINAL_FILE_"NAME" varchar(100) 
	, SIZE varchar(20) 
	, EXTENSION varchar(10) 
	, CONTENTS_"TYPE" varchar(20) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_BASE_DATE (	
	  Id numeric  NOT NULL 
	, BASE_DATE varchar(10) 
	, BASE_YY varchar(4) 
	, BASE_YM varchar(6) 
	, BASE_DW numeric 
	, BASE_DW_"NAME" varchar(50) 
	, BASE_WEEK numeric 
	, LUNAR_DT varchar(50)  ); 

CREATE TABLE TB_CHECKLIST_INFO (	
	  GAME_SEQ numeric  NOT NULL 
	, CHECK_RA varchar(10) 
	, CHECK_RO varchar(10) 
	, CONFIRM_STATE char(1) 
	, CONFIRM_DATE timestamp  ); 

CREATE TABLE TB_COMMENT (	
	  SEQ numeric  NOT NULL 
	, MASTER_SEQ numeric 
	, "TYPE" varchar(5) 
	, ORIGIN_NO numeric 
	, GROUP_ORDER numeric 
	, GROUP_LAYER numeric 
	, CONTENTS varchar(1000) 
	, DEL_YN char(1) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_COMMON_CODE (	
	  CODE varchar(15)  NOT NULL 
	, GROUP_CODE varchar(20)  NOT NULL 
	, LEVEL numeric 
	, "NAME" varchar(100) 
	, DESCRIPTION varchar(1000) 
	, OPTION1 varchar(50) 
	, OPTION2 varchar(50) 
	, OPTION3 varchar(50) 
	, SORT_ORDER numeric 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_DISCUSSION (	
	  SEQ numeric  NOT NULL 
	, SUBJECT varchar(500)  NOT NULL 
	, CONTENTS varchar(1000)  NOT NULL 
	, START_DATE timestamp 
	, END_DATE timestamp 
	, OPEN_YN char(1) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_DISCUSSION_COMMENT (	
	  SEQ numeric  NOT NULL 
	, DISCUSSION_SEQ numeric  NOT NULL 
	, USER_ID varchar(30)  NOT NULL 
	, CONTENTS varchar(1000)  NOT NULL 
	, DEL_YN char(1)  NOT NULL 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_EDU_INFO (	
	  SEQ numeric  NOT NULL 
	, "TYPE" varchar(20) 
	, "YEAR" varchar(5) 
	, COMPETITION varchar(100) 
	, SUBJECT varchar(100) 
	, DESCRIPTION varchar(100) 
	, USE_YN char(1) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_EDU_VOD_INFO (	
	  SEQ numeric  NOT NULL 
	, MASTER_SEQ numeric  NOT NULL 
	, UPLOAD_PATH varchar(300) 
	, FILE_ID varchar(50) 
	, FILE_NAME varchar(100) 
	, ORIGINAL_FILE_"NAME" varchar(100) 
	, EDU_DATE timestamp 
	, EDU_LOCATION varchar(50) 
	, EDU_TEAM1 varchar(30) 
	, EDU_TEAM2 varchar(30) 
	, FILE_SUBJECT varchar(100) 
	, EDU_KEYWORD varchar(300) 
	, EDU_KEYWORD_"NAME" varchar(300) 
	, USE_YN varchar(2) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp  ); 

CREATE TABLE TB_EDU_VOD_REPLY (	
	  SEQ numeric  NOT NULL 
	, EDU_VOD_SEQ numeric  NOT NULL 
	, ORIGIN_NO numeric 
	, GROUP_ORDER numeric 
	, GROUP_LAYER numeric 
	, CONTENT varchar(200) 
	, REG_USER varchar(50) 
	, REG_DATE timestamp 
	, MOD_USER varchar(50) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_EVENT_INFO (	
	  SEQ numeric  NOT NULL 
	, EVENT_NAME varchar(100) 
	, START_DATE timestamp 
	, END_DATE timestamp 
	, EVENT_YEAR varchar(4) 
	, MAJOR_YN char(1) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp 
	, USE_YN char(1)  ); 

CREATE TABLE TB_EVENT_TEAM_INFO (	
	  SEQ numeric  NOT NULL 
	, EVENT_YEAR varchar(4)  NOT NULL 
	, EVENT_SEQ numeric 
	, LEAGUE_CODE varchar(50) 
	, TEAM_SEQ numeric  ); 

CREATE TABLE TB_GAME_CHECK (	
	  GAME_SEQ numeric  NOT NULL 
	, CHECK_CODE varchar(10) 
	, CHECK_NAME varchar(100) 
	, CHECK_TYPE varchar(10) 
	, CHECK_STATE char(1) 
	, CHECK_NOTE varchar(4000) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp  ); 

CREATE TABLE TB_GAME_COMMENT_NotUsed (	
	  SEQ numeric  NOT NULL 
	, GAME_SEQ numeric 
	, GAME_HISTORY_SEQ numeric 
	, USER_ID varchar(30) 
	, CONTENTS varchar(1000) 
	, DEL_YN char(1) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp 
	, "TYPE" varchar(5)  ); 

CREATE TABLE TB_GAME_HISTORY (	
	  SEQ numeric  NOT NULL 
	, GAME_SEQ numeric  NOT NULL 
	, HIST_TEAM varchar(5)  NOT NULL 
	, HIST_HALF varchar(15) 
	, HIST_TIME_MIN varchar(5) 
	, HIST_TIME_SEC varchar(5) 
	, HIST_PLAYER varchar(20) 
	, HIST_JUDGE varchar(10) 
	, HIST_JUDGE_YN char(1) 
	, HIST_MISS_YN char(1) 
	, HIST_VAR_PROTOCOL varchar(5) 
	, HIST_VAR_PROTOCOL_JUDGE varchar(6) 
	, HIST_VAR_REVIEW char(1) 
	, HIST_TIME_SEEK varchar(10) 
	, REG_USER varchar(20) 
	, REG_DATE timestamp 
	, IMG_PATH varchar(300) 
	, NOTICE_YN varchar(1)  ); 

CREATE TABLE TB_GAME_HISTORY_PROTOCOL (	
	  GAME_SEQ numeric  NOT NULL 
	, GAME_HISTORY_SEQ numeric  NOT NULL 
	, CHECK_TIME varchar(10) 
	, REVIEW_CATEGORY varchar(10) 
	, REVIEW_TIME varchar(10) 
	, PROTOCOL_JUDGE varchar(10) 
	, PROTOCOL_RESULT varchar(10) 
	, WRONG_YN char(1) 
	, GRAY_ZONE_YN char(1) 
	, REG_USER varchar(20) 
	, REG_DATE timestamp  ); 

CREATE TABLE TB_GAME_HISTORY_VOD_THUMBNAIL (	
	  GAME_SEQ numeric  NOT NULL 
	, GAME_HISTORY_SEQ numeric  NOT NULL 
	, VOD_INFO_SEQ numeric  NOT NULL 
	, IMG_PATH varchar(2000) 
	, IMG_"NAME" varchar(256)  ); 

CREATE TABLE TB_GAME_HISTORY_WRONG (	
	  SEQ numeric  NOT NULL 
	, GAME_SEQ numeric  NOT NULL 
	, GAME_HISTORY_SEQ numeric  NOT NULL 
	, REF_"TYPE" varchar(10) 
	, WRONG_CODE varchar(10) 
	, MISS_CODE varchar(10) 
	, REG_USER varchar(20) 
	, REG_DATE timestamp  ); 

CREATE TABLE TB_GAME_INFO (	
	  SEQ numeric  NOT NULL 
	, EVENT_SEQ numeric 
	, GAME_ROUND varchar(2) 
	, GAME_"NAME" varchar(100) 
	, GAME_DATE timestamp 
	, GAME_PLACE varchar(50) 
	, TEAM1_SEQ numeric 
	, TEAM2_SEQ numeric 
	, TEAM1_SCORE numeric 
	, TEAM2_SCORE numeric 
	, LEAGUE_CODE varchar(10) 
	, REFEREE varchar(30) 
	, A_REF1 varchar(30) 
	, A_REF2 varchar(30) 
	, FOURTH_REF varchar(30) 
	, VAR varchar(30) 
	, AVAR varchar(30) 
	, REPLAY_OP varchar(30) 
	, REPLAY_AS varchar(30) 
	, BROADCASTER varchar(30) 
	, VOD_FIRST_HALF numeric 
	, VOD_SECOND_HALF numeric 
	, VOD_OVERTIME_FIRST_HALF numeric 
	, VOD_OVERTIME_SECOND_HALF numeric 
	, VOD_FIRST_END numeric 
	, VOD_SECOND_END numeric 
	, VOD_OVERTIME_FIRST_END numeric 
	, VOD_OVERTIME_SECOND_END numeric 
	, OPEN_YN char(1) 
	, END_YN char(1) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp 
	, CONFIRM_STATE char(1) 
	, SUBMIT_DATE timestamp 
	, CONFIRM_DATE timestamp 
	, SENDER_PWD varchar(20) 
	, RECEIVER_PWD varchar(20)  ); 

CREATE TABLE TB_GAME_INFO_AVAR (	
	  SEQ numeric 
	, SUB_SEQ numeric 
	, VAR_PROTOCOL varchar(10) 
	, ORIGINAL_DECISION varchar(10) 
	, JUDGE_REASON varchar(10) 
	, JUDGE_REVIEW varchar(10) 
	, JUDGE_RESULT varchar(10) 
	, MESSAGE_CODE varchar(10) 
	, MESSAGE_SUB_CODE varchar(10) 
	, USE_YN varchar(1) 
	, CUSER varchar(50) 
	, CDATE timestamp 
	, EUSER varchar(50) 
	, EDATE timestamp  ); 

CREATE TABLE TB_GAME_INFO_AVAR_NEW (	
	  SEQ numeric 
	, SUB_SEQ numeric 
	, P1 varchar(10) 
	, P2 varchar(10) 
	, P3 varchar(10) 
	, P4 varchar(10) 
	, MESSAGE_T varchar(100) 
	, MESSAGE_B varchar(100) 
	, USE_YN varchar(1) 
	, CUSER varchar(50) 
	, CDATE timestamp 
	, EUSER varchar(50) 
	, EDATE timestamp  ); 

CREATE TABLE TB_GAME_INFO_AVAR_HISTORY (	
	  SEQ numeric 
	, SUB_SEQ numeric 
	, AVAR_"TYPE" varchar(10) 
	, CUSER varchar(50) 
	, CDATE timestamp  ); 

CREATE TABLE TB_GAME_INFO_AVAR_HISTORY_NEW (	
	  SEQ numeric 
	, SUB_SEQ numeric 
	, P_CODE varchar(10) 
	, CUSER varchar(50) 
	, CDATE timestamp  ); 

CREATE TABLE TB_GAME_INFO_AVAR_MESSAGE (	
	  CODE varchar(10)  NOT NULL 
	, SUB_CODE varchar(10)  NOT NULL 
	, MESSAGE1 varchar(200) 
	, MESSAGE2 varchar(200) 
	, MESSAGE3 varchar(200) 
	, USE_YN varchar(1)  ); 

CREATE TABLE TB_LIVE_INFO (	
	  SEQ numeric  NOT NULL 
	, GAME_SEQ numeric  NOT NULL 
	, SUBJECT varchar(200) 
	, CONTENTS varchar(4000) 
	, CHANNEL numeric 
	, LIVE_YN char(1) 
	, OPEN_YN char(1) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_MENU_ADMIN (	
	  MENU_ID varchar(10)  NOT NULL 
	, MENU_"NAME" varchar(10)  NOT NULL 
	, DEPTH numeric 
	, URL varchar(50) 
	, USE_YN char(1) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_MENU_AUTH (	
	  AUTH_CODE varchar(50)  NOT NULL 
	, MENU_ID varchar(50)  NOT NULL 
	, REG_USER varchar(50) 
	, REG_DATE timestamp  ); 

CREATE TABLE TB_MENU_AUTH_copy (	
	  AUTH_CODE varchar(50)  NOT NULL 
	, MENU_ID varchar(50)  NOT NULL 
	, REG_USER varchar(50) 
	, REG_DATE timestamp  ); 

CREATE TABLE TB_MENU_FRONT (	
	  MENU_ID varchar(10)  NOT NULL 
	, MENU_"NAME" varchar(10)  NOT NULL 
	, DEPTH numeric 
	, URL varchar(50) 
	, USE_YN char(1) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_MENU_INFO (	
	  MENU_ID varchar(50)  NOT NULL 
	, MENU_"NAME" varchar(100) 
	, MENU_PATH varchar(200) 
	, MENU_UPPER varchar(50) 
	, MENU_SORT varchar(50) 
	, MEMO varchar(500) 
	, USE_YN char(1) 
	, REG_DATE timestamp  ); 

CREATE TABLE TB_MENU_INFO_copy (	
	  MENU_ID varchar(50)  NOT NULL 
	, MENU_"NAME" varchar(100) 
	, MENU_PATH varchar(200) 
	, MENU_UPPER varchar(50) 
	, MENU_SORT varchar(50) 
	, MEMO varchar(500) 
	, USE_YN char(1) 
	, REG_DATE timestamp  ); 

CREATE TABLE TB_NEW_GAME_CHECK (	
	  GAME_SEQ numeric  NOT NULL 
	, CHECK_CODE varchar(10) 
	, CHECK_STATE char(1) 
	, CHECK_NOTE varchar(4000) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp  ); 

CREATE TABLE TB_PRICE_INFO (	
	  SEQ numeric  NOT NULL 
	, YEAR varchar(4) 
	, REFEREE_"TYPE" varchar(20) 
	, PRICE numeric  ); 

CREATE TABLE TB_RECORD_FILES (	
	  SEQ numeric  NOT NULL 
	, GAME_SEQ numeric  NOT NULL 
	, UPLOAD_PATH varchar(200) 
	, ORIGINAL_FILE_"NAME" varchar(50) 
	, SAVE_FILE_"NAME" varchar(50) 
	, FILE_"TYPE" varchar(100) 
	, FILE_SIZE varchar(100) 
	, REG_USER varchar(50) 
	, REG_DATE timestamp  ); 

CREATE TABLE TB_REFEREE_GRADE (	
	  GAME_SEQ numeric  NOT NULL 
	, USER_ID varchar(50)  NOT NULL 
	, REF_"TYPE" varchar(5)  NOT NULL 
	, REF_CATEGORY varchar(10)  NOT NULL 
	, GRADE DOUBLE PRECISION 
	, OPTION1 numeric 
	, OPTION2 numeric 
	, OPTION3 numeric 
	, OPTION4 numeric 
	, OPTION5 numeric 
	, OPTION6 numeric 
	, OPTION7 numeric 
	, OPTION8 numeric 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_REFEREE_GRADE_BAK (	
	  GAME_SEQ numeric  NOT NULL 
	, REFEREE_"NAME" varchar(50)  NOT NULL 
	, REFEREE_GRADE DOUBLE PRECISION 
	, REFEREE_CHARGING numeric 
	, REFEREE_PUSHING numeric 
	, REFEREE_KICKING numeric 
	, REFEREE_JUMPING numeric 
	, REFEREE_STRIKING numeric 
	, REFEREE_TACKLE numeric 
	, REFEREE_HOLDING numeric 
	, REFEREE_IMPEDING numeric 
	, REFEREE_SPITTING numeric 
	, REFEREE_TRIPPING numeric 
	, REFEREE_HANDBALL numeric 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_REFEREE_INFO_ORIGIN (	
	  USER_ID varchar(30)  NOT NULL 
	, ATTACH_PLACE varchar(5) 
	, CERTNO_YN char(1) 
	, CERTNO_YEAR varchar(5) 
	, REFEREE_PROIN varchar(5) 
	, REFEREE_WORLDIN varchar(5) 
	, SCHOOL_"NAME"1 varchar(30) 
	, SCHOOL_"NAME"2 varchar(30) 
	, SCHOOL_"NAME"3 varchar(30) 
	, SCHOOL_"NAME"4 varchar(30) 
	, SCHOOL_"NAME"5 varchar(30) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_REFEREE_INFO_PERSONAL (	
	  USER_ID varchar(30)  NOT NULL 
	, REF_"TYPE" varchar(5)  NOT NULL 
	, ACTLEAGUE_"TYPE" varchar(10) 
	, FILE_PATH varchar(50) 
	, FILE_"NAME" varchar(50) 
	, KR_"NAME" varchar(10)  NOT NULL 
	, CN_"NAME" varchar(10)  NOT NULL 
	, EN_"NAME" varchar(20) 
	, JUMIN1 varchar(6) 
	, JUMIN2 varchar(50) 
	, JOB_"NAME" varchar(30) 
	, CORP_"NAME" varchar(30) 
	, HOME_ZIPCODE varchar(5) 
	, HOME_ADDRESS1 varchar(50) 
	, HOME_ADDRESS2 varchar(50) 
	, CORP_ZIPCODE varchar(5) 
	, CORP_ADDRESS1 varchar(50) 
	, CORP_ADDRESS2 varchar(50) 
	, HPNO varchar(15) 
	, HPNO_WIFE varchar(15) 
	, EMAIL varchar(30) 
	, BANK_"NAME" varchar(10) 
	, ACCOUNT_NO varchar(20) 
	, MARRYED_YN char(1) 
	, FAMILY varchar(20) 
	, RELIGION varchar(10) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_REFEREE_INFO_PHYSICAL (	
	  USER_ID varchar(30)  NOT NULL 
	, HEIGHT varchar(5) 
	, WEIGHT varchar(5) 
	, SIGHT_LEFT varchar(5) 
	, SIGHT_RIGHT varchar(5) 
	, EARPHONE_POS varchar(5) 
	, WEAR_SIZE varchar(5) 
	, UNIFORM_SIZE varchar(5) 
	, SHOES_SIZE varchar(5) 
	, SOCCERSHOES_SIZE varchar(5) 
	, MILITARY_"TYPE" varchar(5) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_REFEREE_UPLOAD_DETAIL (	
	  UPLOAD_SEQ numeric  NOT NULL 
	, UPLOAD_DTL_SEQ numeric  NOT NULL 
	, GAME_"NAME" varchar(100) 
	, SEQ numeric 
	, GAME_DATE varchar(10) 
	, GAME_PLACE varchar(200) 
	, GAME_HA varchar(100) 
	, TEAM_"NAME" varchar(100) 
	, REFEREE_NO varchar(30) 
	, REFEREE_"NAME" varchar(30) 
	, REFEREE_POSITION varchar(100) 
	, USER_ID varchar(30) 
	, GAME_MM numeric 
	, GAME_SS numeric 
	, PLAY_MM numeric 
	, PLAY_SS numeric 
	, PLAY_KM DOUBLE PRECISION 
	, PLAY_MINUTE_PER_METER DOUBLE PRECISION 
	, PLAY_KM_PER_HOUR DOUBLE PRECISION 
	, SPRnumeric_COUNT numeric 
	, ACTIVE_AREA_PERCENT DOUBLE PRECISION 
	, Z1 DOUBLE PRECISION 
	, Z2 DOUBLE PRECISION 
	, Z3 DOUBLE PRECISION 
	, Z4 DOUBLE PRECISION 
	, Z5 DOUBLE PRECISION 
	, Z6 DOUBLE PRECISION 
	, Z7 DOUBLE PRECISION 
	, Z8 DOUBLE PRECISION 
	, Z9 DOUBLE PRECISION 
	, Z10 DOUBLE PRECISION 
	, Z11 DOUBLE PRECISION 
	, Z12 DOUBLE PRECISION 
	, Z13 DOUBLE PRECISION 
	, Z14 DOUBLE PRECISION 
	, Z15 DOUBLE PRECISION 
	, STANDING DOUBLE PRECISION 
	, WALKING DOUBLE PRECISION 
	, JOGGING DOUBLE PRECISION 
	, RUNNING DOUBLE PRECISION 
	, HIR DOUBLE PRECISION 
	, SPRnumeric DOUBLE PRECISION  ); 

CREATE TABLE TB_REFEREE_UPLOAD_MASTER (	
	  UPLOAD_SEQ numeric  NOT NULL 
	, EXCEL_FILE_"NAME" varchar(1000) 
	, SYSTEM_FILE_PATH varchar(1000) 
	, SYSTEM_FILE_"NAME" varchar(1000) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp  ); 

CREATE TABLE TB_SURVEY_ANSWER (	
	  SEQ numeric  NOT NULL 
	, USER_ID varchar(30)  NOT NULL 
	, MAIN_SEQ numeric  NOT NULL 
	, QUESTION_SEQ numeric  NOT NULL 
	, MULTIPLE_ANSWER numeric 
	, SUBJECTIVE_ANSWER varchar(500) 
	, ANSWER_DATE timestamp  NOT NULL 
	, USE_YN char(1)  ); 

CREATE TABLE TB_SURVEY_ANSWER_BAK (	
	  USER_ID varchar(30)  NOT NULL 
	, QUESTION_SEQ numeric  NOT NULL 
	, QUESTION_DETAIL_SEQ numeric 
	, ANSWER_CONTENTS varchar(500)  ); 

CREATE TABLE TB_SURVEY_MAIN (	
	  SEQ numeric  NOT NULL 
	, SUBJECT varchar(500) 
	, OBJECTIVE varchar(1000) 
	, CONTENTS varchar(1000) 
	, TARGET varchar(10) 
	, START_DATE timestamp 
	, END_DATE timestamp 
	, OPEN_YN char(1) 
	, BACK_YN char(1) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 


CREATE TABLE TB_SURVEY_QUESTION (	
	  SEQ numeric  NOT NULL 
	, MAIN_SEQ numeric 
	, QUESTION varchar(500) 
	, SORT_ORDER numeric 
	, VOD_SEQ varchar(50) 
	, "TYPE" varchar(20) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_SURVEY_QUESTION_DETAIL (	
	  SEQ numeric  NOT NULL 
	, QUESTION_SEQ numeric 
	, CONTENTS varchar(100) 
	, ANSWER char(1)  ); 

CREATE TABLE TB_SURVEY_QUESTION_FILE (	
	  VOD_SEQ varchar(50)  NOT NULL 
	, MAIN_SEQ numeric  NOT NULL 
	, FILE_PATH varchar(100) 
	, UPLOAD_PATH varchar(100) 
	, FILE_"NAME" varchar(100) 
	, ORIGINAL_FILE_"NAME" varchar(100) 
	, "SIZE" varchar(20) 
	, EXTENSION varchar(10) 
	, CONTENTS_"TYPE" varchar(20) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_TEAM_INFO (	
	  SEQ numeric  NOT NULL 
	, TEAM_"NAME" varchar(30)  NOT NULL 
	, EN_TEAM_"NAME" varchar(50)  NOT NULL 
	, DESCRIPTION varchar(100) 
	, LEAGUE_"TYPE" varchar(10) 
	, KLEAGUE_YN varchar(4) 
	, STATUS varchar(10) 
	, STADIUM_"NAME" varchar(20) 
	, MANAGER_"NAME" varchar(10) 
	, FILE_PATH varchar(100) 
	, UPLOAD_PATH varchar(100) 
	, FILE_"NAME" varchar(50) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_USER (	
	  USER_ID varchar(30)  NOT NULL 
	, "PASSWORD" varchar(50)  NOT NULL 
	, "NAME" varchar(20)  NOT NULL 
	, PHONE varchar(15) 
	, EMAIL varchar(50) 
	, "TYPE" varchar(10) 
	, STATUS varchar(10) 
	, PHOTO numeric 
	, ETC varchar(100) 
	, USE_YN char(1) 
	, STOP_YN char(1) 
	, DELETE_YN char(1) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_USER_TEAM_REL (	
	  TEAM_SEQ numeric  NOT NULL 
	, USER_ID varchar(30)  NOT NULL  ); 

CREATE TABLE TB_VARREPORT_INFO (	
	  SEQ numeric  NOT NULL 
	, GAME_SEQ numeric  NOT NULL 
	, HALF varchar(50) 
	, MINUTE1 varchar(50) 
	, MINUTE2 varchar(50) 
	, INCIDENT varchar(50) 
	, INCIDENT_PK varchar(50) 
	, TEAM varchar(50) 
	, TEAM_NO varchar(50) 
	, DECISION_REF varchar(50) 
	, CARD_REF varchar(50) 
	, CHECK1 varchar(50) 
	, CHECK2 varchar(50) 
	, CHECK3 varchar(50) 
	, REVIEW1 varchar(50) 
	, REVIEW2 varchar(50) 
	, REVIEW3 varchar(50) 
	, REVIEW4 varchar(50) 
	, REVIEW5 varchar(50) 
	, REVIEW6 varchar(50) 
	, COMMENTS varchar(200) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_VAR_CHANNEL (	
	  SEQ numeric  NOT NULL 
	, CH varchar(50) 
	, SENDER_PWD varchar(50) 
	, RECEIVER_PWD varchar(50) 
	, CUR_EVENT varchar(50) 
	, USE_YN varchar(50) 
	, REG_DATE timestamp 
	, UDT_DATE timestamp  ); 

CREATE TABLE TB_VAR_EVENT (	
	  SEQ numeric  NOT NULL 
	, EVE_ORDER1 varchar(2) 
	, EVE_ORDER2 varchar(2) 
	, FILE_"NAME" varchar(200) 
	, FINAL_YN char(1) 
	, OPTION1 varchar(50)  ); 

CREATE TABLE TB_VOD (	
	  SEQ numeric  NOT NULL 
	, SUBJECT varchar(100)  NOT NULL 
	, CONTENTS varchar(1000) 
	, EVENT_"NAME" varchar(100) 
	, GAME_"NAME" varchar(100) 
	, GAME_DATE timestamp 
	, GAME_PLACE varchar(50) 
	, THUMBNAIL numeric 
	, VOD_FILE numeric 
	, OPEN_YN char(1) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_VOD_COMMENT (	
	  SEQ numeric  NOT NULL 
	, VOD_SEQ numeric 
	, USER_ID varchar(30) 
	, CONTENTS varchar(1000) 
	, DEL_YN char(1) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_VOD_FILE_INFO (	
	  SEQ numeric  NOT NULL 
	, GAME_SEQ numeric  NOT NULL 
	, FILE_PATH varchar(100) 
	, UPLOAD_PATH varchar(100) 
	, FILE_"NAME" varchar(100) 
	, ORIGINAL_FILE_"NAME" varchar(100) 
	, SIZE varchar(20) 
	, EXTENSION varchar(10) 
	, CONTENTS_"TYPE" varchar(20) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_VOD_FILE_INFO_copy (	
	  SEQ numeric  NOT NULL 
	, GAME_SEQ numeric  NOT NULL 
	, FILE_PATH varchar(100) 
	, UPLOAD_PATH varchar(100) 
	, FILE_"NAME" varchar(100) 
	, ORIGINAL_FILE_"NAME" varchar(100) 
	, SIZE varchar(20) 
	, EXTENSION varchar(10) 
	, CONTENTS_"TYPE" varchar(20) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp  ); 

CREATE TABLE TB_VOD_INFO (	
	  SEQ numeric  NOT NULL 
	, GAME_SEQ numeric  NOT NULL 
	, VOD_"NAME" varchar(100) 
	, FILE_"NAME" varchar(100) 
	, INSTANCE_ID varchar(100) 
	, FILE_ID varchar(100) 
	, CAMERA_CODE varchar(10) 
	, OPEN_YN char(1) 
	, REG_USER varchar(30) 
	, REG_DATE timestamp 
	, MOD_USER varchar(30) 
	, MOD_DATE timestamp 
	, FIRST_TOTAL_SEC numeric 
	, SECOND_TOTAL_SEC numeric 
	, UPLOAD_"TYPE" varchar(2)  ); 

CREATE TABLE TB_VOD_"TYPE" (	
	  VOD_SEQ numeric  NOT NULL 
	, "TYPE"_CODE varchar(10)  NOT NULL  ); 

CREATE TABLE tm_file (	
	  FILE_SEQ char(36)  NOT NULL 
	, REAL_FILE_"NAME" varchar(255) 
	, SERVER_FILE_"NAME" varchar(255) 
	, PHYSICAL_PATH varchar(500) 
	, CREATE_DATE timestamp 
	, CONVERT_STATE char(1) 
	, STATE char(1) 
	, FOLDER_SEQ char(36) 
	, FILE_SIZE numeric 
	, PLAY_TIME varchar(10) 
	, AUDIO_FORMAT varchar(200) 
	, VIDEO_FORMAT varchar(200) 
	, INSTANCE_SEQ char(36) 
	, AUDIO_CODEC varchar(20) 
	, VIDEO_CODEC varchar(20) 
	, VIDEO_SIZE varchar(10) 
	, SMIL_FILE varchar(500)  ); 



ALTER TABLE LOGIN_HISTORY ADD CONSTRAINT PK_LOGIN_HISTORY PRIMARY KEY(SEQ) ;
ALTER TABLE TB_ADMIN_USER ADD CONSTRAINT PK_TB_ADMIN_USER PRIMARY KEY(USER_ID) ;
ALTER TABLE TB_APT_INFO ADD CONSTRAINT PK_TB_APT_INFO PRIMARY KEY(SEQ) ;
ALTER TABLE TB_ASSIGN_STOP ADD CONSTRAINT PK_TB_ASSIGN_STOP PRIMARY KEY(SEQ) ;
ALTER TABLE TB_ATTACH_FILE ADD CONSTRAINT PK_TB_ATTACH_FILE PRIMARY KEY(SEQ) ;
ALTER TABLE TB_BASE_DATE ADD CONSTRAINT PK_TB_BASE_DATE PRIMARY KEY(ID) ;
ALTER TABLE TB_COMMENT ADD CONSTRAINT PK_TB_COMMENT PRIMARY KEY(SEQ) ;
ALTER TABLE TB_COMMON_CODE ADD CONSTRAINT PK_TB_COMMON_CODE PRIMARY KEY(CODE, GROUP_CODE) ;

ALTER TABLE TB_DISCUSSION ADD CONSTRAINT PK_TB_DISCUSSION PRIMARY KEY(SEQ) ;
ALTER TABLE TB_DISCUSSION_COMMENT ADD CONSTRAINT PK_TB_DISCUSSION_COMMENT PRIMARY KEY(SEQ) ;
ALTER TABLE TB_EDU_INFO ADD CONSTRAINT PK_TB_EDU_INFO PRIMARY KEY(SEQ) ;
ALTER TABLE TB_EDU_VOD_INFO ADD CONSTRAINT PK_TB_EDU_VOD_INFO PRIMARY KEY(SEQ) ;
ALTER TABLE TB_EDU_VOD_REPLY ADD CONSTRAINT PK_TB_EDU_VOD_REPLY PRIMARY KEY(SEQ) ;
ALTER TABLE TB_EVENT_INFO ADD CONSTRAINT PK_TB_EVENT_INFO PRIMARY KEY(SEQ) ;
ALTER TABLE TB_EVENT_TEAM_INFO ADD CONSTRAINT PK_TB_EVENT_TEAM_INFO PRIMARY KEY(SEQ) ;
ALTER TABLE TB_GAME_COMMENT_NotUsed ADD CONSTRAINT PK_TB_GAME_COMMENT_NotUsed PRIMARY KEY(SEQ) ;
ALTER TABLE TB_GAME_HISTORY ADD CONSTRAINT PK_TB_GAME_HISTORY PRIMARY KEY(SEQ) ;
ALTER TABLE TB_GAME_HISTORY_PROTOCOL ADD CONSTRAINT PK_TB_GAME_HISTORY_PROTOCOL PRIMARY KEY(GAME_SEQ, GAME_HISTORY_SEQ) ;

ALTER TABLE TB_GAME_HISTORY_VOD_THUMBNAIL ADD CONSTRAINT PK_TB_GAME_HISTORY_VOD_THUMBNAIL PRIMARY KEY(GAME_SEQ,GAME_HISTORY_SEQ,VOD_INFO_SEQ) ;


ALTER TABLE TB_GAME_HISTORY_WRONG ADD CONSTRAINT PK_TB_GAME_HISTORY_WRONG PRIMARY KEY(SEQ,GAME_SEQ,GAME_HISTORY_SEQ) ;


ALTER TABLE TB_GAME_INFO ADD CONSTRAINT PK_TB_GAME_INFO PRIMARY KEY(SEQ) ;
ALTER TABLE TB_LIVE_INFO ADD CONSTRAINT PK_TB_LIVE_INFO PRIMARY KEY(SEQ) ;
ALTER TABLE TB_MENU_ADMIN ADD CONSTRAINT PK_TB_MENU_ADMIN PRIMARY KEY(MENU_ID) ;
ALTER TABLE TB_MENU_AUTH ADD CONSTRAINT PK_TB_MENU_AUTH PRIMARY KEY(AUTH_CODE, MENU_ID) ;

ALTER TABLE TB_MENU_AUTH_copy ADD CONSTRAINT PK_TB_MENU_AUTH_copy PRIMARY KEY(AUTH_CODE, MENU_ID) ;

ALTER TABLE TB_MENU_FRONT ADD CONSTRAINT PK_TB_MENU_FRONT PRIMARY KEY(MENU_ID) ;
ALTER TABLE TB_MENU_INFO ADD CONSTRAINT PK_TB_MENU_INFO PRIMARY KEY(MENU_ID) ;
ALTER TABLE TB_MENU_INFO_copy ADD CONSTRAINT PK_TB_MENU_INFO_copy PRIMARY KEY(MENU_ID) ;
ALTER TABLE TB_PRICE_INFO ADD CONSTRAINT PK_TB_PRICE_INFO PRIMARY KEY(SEQ) ;
ALTER TABLE TB_RECORD_FILES ADD CONSTRAINT PK_TB_RECORD_FILES PRIMARY KEY(SEQ) ;
ALTER TABLE TB_REFEREE_GRADE_BAK ADD CONSTRAINT PK_TB_REFEREE_GRADE_BAK PRIMARY KEY(GAME_SEQ) ;
ALTER TABLE TB_REFEREE_INFO_ORIGIN ADD CONSTRAINT PK_TB_REFEREE_INFO_ORIGIN PRIMARY KEY(USER_ID) ;
ALTER TABLE TB_REFEREE_INFO_PERSONAL ADD CONSTRAINT PK_TB_REFEREE_INFO_PERSONAL PRIMARY KEY(USER_ID) ;
ALTER TABLE TB_REFEREE_INFO_PHYSICAL ADD CONSTRAINT PK_TB_REFEREE_INFO_PHYSICAL PRIMARY KEY(USER_ID) ;
ALTER TABLE TB_REFEREE_UPLOAD_DETAIL ADD CONSTRAINT PK_TB_REFEREE_UPLOAD_DETAIL PRIMARY KEY(UPLOAD_SEQ,UPLOAD_DTL_SEQ) ;

ALTER TABLE TB_REFEREE_UPLOAD_MASTER ADD CONSTRAINT PK_TB_REFEREE_UPLOAD_MASTER PRIMARY KEY(UPLOAD_SEQ) ;
ALTER TABLE TB_SURVEY_ANSWER ADD CONSTRAINT PK_TB_SURVEY_ANSWER PRIMARY KEY(USER_ID, MAIN_SEQ, SEQ) ;


ALTER TABLE TB_SURVEY_MAIN ADD CONSTRAINT PK_TB_SURVEY_MAIN PRIMARY KEY(SEQ) ;
ALTER TABLE TB_SURVEY_QUESTION ADD CONSTRAINT PK_TB_SURVEY_QUESTION PRIMARY KEY(SEQ) ;
ALTER TABLE TB_SURVEY_QUESTION_FILE ADD CONSTRAINT PK_TB_SURVEY_QUESTION_FILE PRIMARY KEY(VOD_SEQ) ;
ALTER TABLE TB_TEAM_INFO ADD CONSTRAINT PK_TB_TEAM_INFO PRIMARY KEY(SEQ) ;
ALTER TABLE TB_USER ADD CONSTRAINT PK_TB_USER PRIMARY KEY(USER_ID) ;
ALTER TABLE TB_USER_TEAM_REL ADD CONSTRAINT PK_TB_USER_TEAM_REL PRIMARY KEY(TEAM_SEQ, USER_ID) ;

ALTER TABLE TB_VARREPORT_INFO ADD CONSTRAINT PK_TB_VARREPORT_INFO PRIMARY KEY(SEQ) ;
ALTER TABLE TB_VAR_CHANNEL ADD CONSTRAINT PK_TB_VAR_CHANNEL PRIMARY KEY(SEQ) ;
ALTER TABLE TB_VAR_EVENT ADD CONSTRAINT PK_TB_VAR_EVENT PRIMARY KEY(SEQ) ;
ALTER TABLE TB_VOD ADD CONSTRAINT PK_TB_VOD PRIMARY KEY(SEQ) ;
ALTER TABLE TB_VOD_COMMENT ADD CONSTRAINT PK_TB_VOD_COMMENT PRIMARY KEY(SEQ) ;
ALTER TABLE TB_VOD_FILE_INFO ADD CONSTRAINT PK_TB_VOD_FILE_INFO PRIMARY KEY(SEQ) ;
ALTER TABLE TB_VOD_FILE_INFO_copy ADD CONSTRAINT PK_TB_VOD_FILE_INFO_copy PRIMARY KEY(SEQ) ;
ALTER TABLE TB_VOD_INFO ADD CONSTRAINT PK_TB_VOD_INFO PRIMARY KEY(SEQ) ;
ALTER TABLE TB_VOD_"TYPE" ADD CONSTRAINT PK_TB_VOD_"TYPE" PRIMARY KEY(VOD_SEQ, "TYPE"_CODE) ;


COMMENT ON TABLE LOGIN_HISTORY IS '로그인기록';
COMMENT ON TABLE TB_ACCESS_LOG IS '접속기록';
COMMENT ON TABLE TB_ADMIN_USER IS '관리자';
COMMENT ON TABLE TB_APT_INFO IS 'APT(실제경기시간) 정보';
COMMENT ON TABLE TB_ASSIGN_STOP IS '배정정지 테이블';
COMMENT ON TABLE TB_ATTACH_FILE IS '첨부파일';
COMMENT ON TABLE TB_BASE_DATE IS '날자기준정보';
COMMENT ON TABLE TB_CHECKLIST_INFO IS 'RA체크리스트 정보';
COMMENT ON TABLE TB_COMMENT IS '영상댓글';
COMMENT ON TABLE TB_COMMON_CODE IS '공통코드';
COMMENT ON TABLE TB_DISCUSSION IS '토론관리';
COMMENT ON TABLE TB_DISCUSSION_COMMENT IS '토론댓글';
COMMENT ON TABLE TB_EDU_INFO IS '경기정보';
COMMENT ON TABLE TB_EDU_VOD_INFO IS '첨부파일';
COMMENT ON TABLE TB_EDU_VOD_REPLY IS 'VOD 답글';
COMMENT ON TABLE TB_EVENT_INFO IS '대회정보';
COMMENT ON TABLE TB_EVENT_TEAM_INFO IS '대회 소속 팀';
COMMENT ON TABLE TB_GAME_CHECK IS '업무관리 테이블';
COMMENT ON TABLE TB_GAME_COMMENT_NotUsed IS '영상댓글';
COMMENT ON TABLE TB_GAME_HISTORY IS '';
COMMENT ON TABLE TB_GAME_HISTORY_PROTOCOL IS '';
COMMENT ON TABLE TB_GAME_HISTORY_VOD_THUMBNAIL IS '';
COMMENT ON TABLE TB_GAME_HISTORY_WRONG IS '오심체크 테이블';
COMMENT ON TABLE TB_GAME_INFO IS '경기정보';
COMMENT ON TABLE TB_GAME_INFO_AVAR IS 'AVAR 정보저장';
COMMENT ON TABLE TB_GAME_INFO_AVAR_HISTORY IS 'AVAR HISTORY TABLE';
COMMENT ON TABLE TB_GAME_INFO_AVAR_HISTORY_NEW IS '';
COMMENT ON TABLE TB_GAME_INFO_AVAR_MESSAGE IS '';
COMMENT ON TABLE TB_GAME_INFO_AVAR_NEW IS '';
COMMENT ON TABLE TB_LIVE_INFO IS '생방송정보';
COMMENT ON TABLE TB_MENU_ADMIN IS '관리자화면메뉴관리';
COMMENT ON TABLE TB_MENU_AUTH IS '권한별 메뉴';
COMMENT ON TABLE TB_MENU_AUTH_copy IS '권한별 메뉴';
COMMENT ON TABLE TB_MENU_FRONT IS '사용자화면메뉴관리';
COMMENT ON TABLE TB_MENU_INFO IS '메뉴정보';
COMMENT ON TABLE TB_MENU_INFO_copy IS '메뉴정보';
COMMENT ON TABLE TB_NEW_GAME_CHECK IS '업무관리 테이블';
COMMENT ON TABLE TB_PRICE_INFO IS '심판출장비 관리';
COMMENT ON TABLE TB_RECORD_FILES IS '검사지 파일';
COMMENT ON TABLE TB_REFEREE_GRADE IS '심판 점수관리';
COMMENT ON TABLE TB_REFEREE_GRADE_BAK IS '심판 점수관리';
COMMENT ON TABLE TB_REFEREE_INFO_ORIGIN IS '심판 기본정보관리';
COMMENT ON TABLE TB_REFEREE_INFO_PERSONAL IS '심판 개인정보';
COMMENT ON TABLE TB_REFEREE_INFO_PHYSICAL IS '심판 신체정보';
COMMENT ON TABLE TB_REFEREE_UPLOAD_DETAIL IS '';
COMMENT ON TABLE TB_REFEREE_UPLOAD_MASTER IS '';
COMMENT ON TABLE TB_SURVEY_ANSWER IS '설문답변';
COMMENT ON TABLE TB_SURVEY_ANSWER_BAK IS '설문답변';
COMMENT ON TABLE TB_SURVEY_MAIN IS '설문메인';
COMMENT ON TABLE TB_SURVEY_QUESTION IS '설문문항';
COMMENT ON TABLE TB_SURVEY_QUESTION_DETAIL IS '문항상세';
COMMENT ON TABLE TB_SURVEY_QUESTION_FILE IS '첨부파일';
COMMENT ON TABLE TB_TEAM_INFO IS '팀정보';
COMMENT ON TABLE TB_USER IS '회원정보';
COMMENT ON TABLE TB_USER_TEAM_REL IS '유저팀관계';
COMMENT ON TABLE TB_VARREPORT_INFO IS 'VAR 기록지';
COMMENT ON TABLE TB_VAR_CHANNEL IS '';
COMMENT ON TABLE TB_VAR_EVENT IS '';
COMMENT ON TABLE TB_VOD IS '영상정보';
COMMENT ON TABLE TB_VOD_COMMENT IS '영상댓글';
COMMENT ON TABLE TB_VOD_FILE_INFO IS '첨부파일';
COMMENT ON TABLE TB_VOD_FILE_INFO_copy IS '첨부파일';
COMMENT ON TABLE TB_VOD_INFO IS '영상정보';
COMMENT ON TABLE TB_VOD_"TYPE" IS '영상종류';
COMMENT ON TABLE tm_file IS '';

COMMENT ON COLUMN LOGIN_HISTORY.SEQ IS '';
COMMENT ON COLUMN LOGIN_HISTORY.USER_ID IS '회원ID';
COMMENT ON COLUMN LOGIN_HISTORY.USER_IP IS 'IP';
COMMENT ON COLUMN LOGIN_HISTORY.USER_AGENT IS '사용자접속정보';
COMMENT ON COLUMN LOGIN_HISTORY.LOGIN_DATE IS '로그인시간';
COMMENT ON COLUMN TB_ACCESS_LOG.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN TB_ACCESS_LOG.USER_ID IS '회원ID';
COMMENT ON COLUMN TB_ACCESS_LOG.REFERER IS '이전페이지';
COMMENT ON COLUMN TB_ACCESS_LOG.USER_IP IS '아이피';
COMMENT ON COLUMN TB_ACCESS_LOG.USER_AGENT IS '브라우저';
COMMENT ON COLUMN TB_ACCESS_LOG.ACCESS_DATE IS '접속시간';
COMMENT ON COLUMN TB_ADMIN_USER.USER_ID IS '관리자ID';
COMMENT ON COLUMN TB_ADMIN_USER."PASSWORD" IS '비밀번호';
COMMENT ON COLUMN TB_ADMIN_USER."NAME" IS '이름';
COMMENT ON COLUMN TB_ADMIN_USER.EN_"NAME" IS '영어이름';
COMMENT ON COLUMN TB_ADMIN_USER."TYPE" IS '관리자구분';
COMMENT ON COLUMN TB_ADMIN_USER.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_ADMIN_USER.REG_USER IS '등록자';
COMMENT ON COLUMN TB_ADMIN_USER.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_ADMIN_USER.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_ADMIN_USER.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_APT_INFO.SEQ IS 'seq';
COMMENT ON COLUMN TB_APT_INFO.GAME_SEQ IS '경기seq';
COMMENT ON COLUMN TB_APT_INFO.FIRST_APT_MIN IS '전반(분)';
COMMENT ON COLUMN TB_APT_INFO.FIRST_APT_SEC IS '전반(초)';
COMMENT ON COLUMN TB_APT_INFO.SECOND_APT_MIN IS '후반(분)';
COMMENT ON COLUMN TB_APT_INFO.SECOND_APT_SEC IS '후반(초)';
COMMENT ON COLUMN TB_APT_INFO.TOTAL_APT_MIN IS '합계(분)';
COMMENT ON COLUMN TB_APT_INFO.TOTAL_APT_SEC IS '합계(초)';
COMMENT ON COLUMN TB_APT_INFO.REG_USER IS '유저';
COMMENT ON COLUMN TB_APT_INFO.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_ASSIGN_STOP.SEQ IS 'seq';
COMMENT ON COLUMN TB_ASSIGN_STOP.GAME_SEQ IS '게임seq';
COMMENT ON COLUMN TB_ASSIGN_STOP.GAME_HISTORY_SEQ IS '게임히스토리seq';
COMMENT ON COLUMN TB_ASSIGN_STOP.GAME_HISTORY_WRONG_SEQ IS '게임히스토리오심seq';
COMMENT ON COLUMN TB_ASSIGN_STOP.ADVANTAGE_TEAM IS '이득본팀';
COMMENT ON COLUMN TB_ASSIGN_STOP.DISADVANTAGE_TEAM IS '손해본팀';
COMMENT ON COLUMN TB_ASSIGN_STOP.EFFECT_YN IS '승패영향';
COMMENT ON COLUMN TB_ASSIGN_STOP.STOP_DAY IS '정지일수';
COMMENT ON COLUMN TB_ASSIGN_STOP.NOTE IS '비고';
COMMENT ON COLUMN TB_ASSIGN_STOP.REG_USER IS '작성자';
COMMENT ON COLUMN TB_ASSIGN_STOP.REG_DATE IS '작성일';
COMMENT ON COLUMN TB_ASSIGN_STOP.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_ASSIGN_STOP.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_ATTACH_FILE.SEQ IS '';
COMMENT ON COLUMN TB_ATTACH_FILE.GROUP_SEQ IS '파일GROUP번호';
COMMENT ON COLUMN TB_ATTACH_FILE.FILE_PATH IS '파일경로';
COMMENT ON COLUMN TB_ATTACH_FILE.FILE_"NAME" IS '파일명';
COMMENT ON COLUMN TB_ATTACH_FILE.ORIGINAL_FILE_"NAME" IS '원본파일명';
COMMENT ON COLUMN TB_ATTACH_FILE.SIZE IS '파일크기';
COMMENT ON COLUMN TB_ATTACH_FILE.EXTENSION IS '확장자';
COMMENT ON COLUMN TB_ATTACH_FILE.CONTENTS_"TYPE" IS '파일종류';
COMMENT ON COLUMN TB_ATTACH_FILE.REG_USER IS '등록자';
COMMENT ON COLUMN TB_ATTACH_FILE.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_ATTACH_FILE.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_ATTACH_FILE.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_BASE_DATE.Id IS '번호';
COMMENT ON COLUMN TB_BASE_DATE.BASE_DATE IS '기준일';
COMMENT ON COLUMN TB_BASE_DATE.BASE_YY IS '기준년';
COMMENT ON COLUMN TB_BASE_DATE.BASE_YM IS '기준년월';
COMMENT ON COLUMN TB_BASE_DATE.BASE_DW IS '기준요일';
COMMENT ON COLUMN TB_BASE_DATE.BASE_DW_"NAME" IS '기준요일명';
COMMENT ON COLUMN TB_BASE_DATE.BASE_WEEK IS '기준주';
COMMENT ON COLUMN TB_BASE_DATE.LUNAR_DT IS '음력';
COMMENT ON COLUMN TB_CHECKLIST_INFO.GAME_SEQ IS 'GAME_SEQ';
COMMENT ON COLUMN TB_CHECKLIST_INFO.CHECK_RA IS 'RA';
COMMENT ON COLUMN TB_CHECKLIST_INFO.CHECK_RO IS 'RO';
COMMENT ON COLUMN TB_CHECKLIST_INFO.CONFIRM_STATE IS '';
COMMENT ON COLUMN TB_CHECKLIST_INFO.CONFIRM_DATE IS '최종승인날짜';
COMMENT ON COLUMN TB_COMMENT.SEQ IS '';
COMMENT ON COLUMN TB_COMMENT.MASTER_SEQ IS '마스터번호';
COMMENT ON COLUMN TB_COMMENT."TYPE" IS '타입(GAME,EVENT,EDU)';
COMMENT ON COLUMN TB_COMMENT.ORIGIN_NO IS '원글번호';
COMMENT ON COLUMN TB_COMMENT.GROUP_ORDER IS '원글순서';
COMMENT ON COLUMN TB_COMMENT.GROUP_LAYER IS '답글계층';
COMMENT ON COLUMN TB_COMMENT.CONTENTS IS '댓글내용';
COMMENT ON COLUMN TB_COMMENT.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TB_COMMENT.REG_USER IS '작성자ID';
COMMENT ON COLUMN TB_COMMENT.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_COMMENT.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_COMMENT.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_COMMON_CODE.CODE IS '코드';
COMMENT ON COLUMN TB_COMMON_CODE.GROUP_CODE IS '그룹코드(상위코드)';
COMMENT ON COLUMN TB_COMMON_CODE.LEVEL IS '코드레벨';
COMMENT ON COLUMN TB_COMMON_CODE."NAME" IS '코드명';
COMMENT ON COLUMN TB_COMMON_CODE.DESCRIPTION IS '코드설명';
COMMENT ON COLUMN TB_COMMON_CODE.OPTION1 IS 'OPTION1';
COMMENT ON COLUMN TB_COMMON_CODE.OPTION2 IS 'OPTION2';
COMMENT ON COLUMN TB_COMMON_CODE.OPTION3 IS 'OPTION3';
COMMENT ON COLUMN TB_COMMON_CODE.SORT_ORDER IS '순번';
COMMENT ON COLUMN TB_COMMON_CODE.REG_USER IS '등록자';
COMMENT ON COLUMN TB_COMMON_CODE.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_COMMON_CODE.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_COMMON_CODE.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_DISCUSSION.SEQ IS '';
COMMENT ON COLUMN TB_DISCUSSION.SUBJECT IS '제목';
COMMENT ON COLUMN TB_DISCUSSION.CONTENTS IS '내용';
COMMENT ON COLUMN TB_DISCUSSION.START_DATE IS '시작일';
COMMENT ON COLUMN TB_DISCUSSION.END_DATE IS '종료일';
COMMENT ON COLUMN TB_DISCUSSION.OPEN_YN IS '공개여부';
COMMENT ON COLUMN TB_DISCUSSION.REG_USER IS '등록자';
COMMENT ON COLUMN TB_DISCUSSION.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_DISCUSSION.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_DISCUSSION.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_DISCUSSION_COMMENT.SEQ IS '';
COMMENT ON COLUMN TB_DISCUSSION_COMMENT.DISCUSSION_SEQ IS '토론글SEQ';
COMMENT ON COLUMN TB_DISCUSSION_COMMENT.USER_ID IS '작성자ID';
COMMENT ON COLUMN TB_DISCUSSION_COMMENT.CONTENTS IS '작성글';
COMMENT ON COLUMN TB_DISCUSSION_COMMENT.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TB_DISCUSSION_COMMENT.REG_DATE IS '작성일';
COMMENT ON COLUMN TB_DISCUSSION_COMMENT.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_DISCUSSION_COMMENT.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_EDU_INFO.SEQ IS '';
COMMENT ON COLUMN TB_EDU_INFO."TYPE" IS '구분';
COMMENT ON COLUMN TB_EDU_INFO.YEAR IS '년도';
COMMENT ON COLUMN TB_EDU_INFO.COMPETITION IS '대회';
COMMENT ON COLUMN TB_EDU_INFO.SUBJECT IS '제목';
COMMENT ON COLUMN TB_EDU_INFO.DESCRIPTION IS '설명';
COMMENT ON COLUMN TB_EDU_INFO.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_EDU_INFO.REG_USER IS '등록자';
COMMENT ON COLUMN TB_EDU_INFO.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_EDU_INFO.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_EDU_INFO.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_EDU_VOD_INFO.SEQ IS '';
COMMENT ON COLUMN TB_EDU_VOD_INFO.MASTER_SEQ IS '파일GROUP번호';
COMMENT ON COLUMN TB_EDU_VOD_INFO.UPLOAD_PATH IS '업로드경로';
COMMENT ON COLUMN TB_EDU_VOD_INFO.FILE_ID IS '파일아이디';
COMMENT ON COLUMN TB_EDU_VOD_INFO.FILE_"NAME" IS '파일명';
COMMENT ON COLUMN TB_EDU_VOD_INFO.ORIGINAL_FILE_"NAME" IS '원본파일명';
COMMENT ON COLUMN TB_EDU_VOD_INFO.EDU_DATE IS '날짜';
COMMENT ON COLUMN TB_EDU_VOD_INFO.EDU_LOCATION IS '장소';
COMMENT ON COLUMN TB_EDU_VOD_INFO.EDU_TEAM1 IS '팀1';
COMMENT ON COLUMN TB_EDU_VOD_INFO.EDU_TEAM2 IS '팀2';
COMMENT ON COLUMN TB_EDU_VOD_INFO.FILE_SUBJECT IS '파일제목';
COMMENT ON COLUMN TB_EDU_VOD_INFO.EDU_KEYWORD IS '키워드 코드';
COMMENT ON COLUMN TB_EDU_VOD_INFO.EDU_KEYWORD_"NAME" IS '키워드 이름';
COMMENT ON COLUMN TB_EDU_VOD_INFO.USE_YN IS '공개여부';
COMMENT ON COLUMN TB_EDU_VOD_INFO.REG_USER IS '등록자';
COMMENT ON COLUMN TB_EDU_VOD_INFO.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_EDU_VOD_REPLY.SEQ IS 'SEQ';
COMMENT ON COLUMN TB_EDU_VOD_REPLY.EDU_VOD_SEQ IS 'EDU_VOD_INFO SEQ';
COMMENT ON COLUMN TB_EDU_VOD_REPLY.ORIGIN_NO IS '원글 번호';
COMMENT ON COLUMN TB_EDU_VOD_REPLY.GROUP_ORDER IS '원글 순서';
COMMENT ON COLUMN TB_EDU_VOD_REPLY.GROUP_LAYER IS '답글 계층';
COMMENT ON COLUMN TB_EDU_VOD_REPLY.CONTENT IS '답글 내용';
COMMENT ON COLUMN TB_EDU_VOD_REPLY.REG_USER IS '작성자';
COMMENT ON COLUMN TB_EDU_VOD_REPLY.REG_DATE IS '작성일';
COMMENT ON COLUMN TB_EDU_VOD_REPLY.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_EDU_VOD_REPLY.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_EVENT_INFO.SEQ IS '';
COMMENT ON COLUMN TB_EVENT_INFO.EVENT_"NAME" IS '대회명';
COMMENT ON COLUMN TB_EVENT_INFO.START_DATE IS '대회시작일';
COMMENT ON COLUMN TB_EVENT_INFO.END_DATE IS '대회종료일';
COMMENT ON COLUMN TB_EVENT_INFO.EVENT_YEAR IS '대회년도';
COMMENT ON COLUMN TB_EVENT_INFO.MAJOR_YN IS '';
COMMENT ON COLUMN TB_EVENT_INFO.REG_USER IS '등록자';
COMMENT ON COLUMN TB_EVENT_INFO.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_EVENT_INFO.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_EVENT_INFO.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_EVENT_INFO.USE_YN IS '사용자 공개여부';
COMMENT ON COLUMN TB_EVENT_TEAM_INFO.SEQ IS 'SEQ';
COMMENT ON COLUMN TB_EVENT_TEAM_INFO.EVENT_YEAR IS '년도';
COMMENT ON COLUMN TB_EVENT_TEAM_INFO.EVENT_SEQ IS '대회 SEQ';
COMMENT ON COLUMN TB_EVENT_TEAM_INFO.LEAGUE_CODE IS '리그 CODE명';
COMMENT ON COLUMN TB_EVENT_TEAM_INFO.TEAM_SEQ IS '팀 SEQ';
COMMENT ON COLUMN TB_GAME_CHECK.GAME_SEQ IS 'MAIN_SEQ';
COMMENT ON COLUMN TB_GAME_CHECK.CHECK_CODE IS '체크목록';
COMMENT ON COLUMN TB_GAME_CHECK.CHECK_"NAME" IS '체크목록명';
COMMENT ON COLUMN TB_GAME_CHECK.CHECK_"TYPE" IS '체크구분';
COMMENT ON COLUMN TB_GAME_CHECK.CHECK_STATE IS '상태';
COMMENT ON COLUMN TB_GAME_CHECK.CHECK_NOTE IS '비고';
COMMENT ON COLUMN TB_GAME_CHECK.REG_USER IS '작성자';
COMMENT ON COLUMN TB_GAME_CHECK.REG_DATE IS '작성일';
COMMENT ON COLUMN TB_GAME_COMMENT_NotUsed.SEQ IS '';
COMMENT ON COLUMN TB_GAME_COMMENT_NotUsed.GAME_SEQ IS '게임번호';
COMMENT ON COLUMN TB_GAME_COMMENT_NotUsed.GAME_HISTORY_SEQ IS '이벤트 번호';
COMMENT ON COLUMN TB_GAME_COMMENT_NotUsed.USER_ID IS '작성자ID';
COMMENT ON COLUMN TB_GAME_COMMENT_NotUsed.CONTENTS IS '댓글내용';
COMMENT ON COLUMN TB_GAME_COMMENT_NotUsed.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TB_GAME_COMMENT_NotUsed.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_GAME_COMMENT_NotUsed.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_GAME_COMMENT_NotUsed.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_GAME_COMMENT_NotUsed."TYPE" IS '댓글타입';
COMMENT ON COLUMN TB_GAME_HISTORY.SEQ IS '시퀀스';
COMMENT ON COLUMN TB_GAME_HISTORY.GAME_SEQ IS '게임시퀀스';
COMMENT ON COLUMN TB_GAME_HISTORY.HIST_TEAM IS '이벤트발생팀';
COMMENT ON COLUMN TB_GAME_HISTORY.HIST_HALF IS '이벤트전후반';
COMMENT ON COLUMN TB_GAME_HISTORY.HIST_TIME_MIN IS '이벤트발생시간(분)';
COMMENT ON COLUMN TB_GAME_HISTORY.HIST_TIME_SEC IS '이벤트발생시간(초)';
COMMENT ON COLUMN TB_GAME_HISTORY.HIST_PLAYER IS '이벤트발생선수';
COMMENT ON COLUMN TB_GAME_HISTORY.HIST_JUDGE IS '이벤트에대한판정';
COMMENT ON COLUMN TB_GAME_HISTORY.HIST_JUDGE_YN IS '미판정(오심)';
COMMENT ON COLUMN TB_GAME_HISTORY.HIST_MISS_YN IS '오적용(오심)';
COMMENT ON COLUMN TB_GAME_HISTORY.HIST_VAR_PROTOCOL IS '이벤트VAR프로토콜';
COMMENT ON COLUMN TB_GAME_HISTORY.HIST_VAR_PROTOCOL_JUDGE IS '이벤트VAR프로토콜판정';
COMMENT ON COLUMN TB_GAME_HISTORY.HIST_VAR_REVIEW IS '이벤트VAR리뷰여부';
COMMENT ON COLUMN TB_GAME_HISTORY.HIST_TIME_SEEK IS '이벤트발생시간(seek)';
COMMENT ON COLUMN TB_GAME_HISTORY.REG_USER IS '작성자';
COMMENT ON COLUMN TB_GAME_HISTORY.REG_DATE IS '작성일';
COMMENT ON COLUMN TB_GAME_HISTORY.IMG_PATH IS '';
COMMENT ON COLUMN TB_GAME_HISTORY.NOTICE_YN IS '구단공지여부';
COMMENT ON COLUMN TB_GAME_HISTORY_PROTOCOL.GAME_SEQ IS '게임번호';
COMMENT ON COLUMN TB_GAME_HISTORY_PROTOCOL.GAME_HISTORY_SEQ IS '이벤트번호';
COMMENT ON COLUMN TB_GAME_HISTORY_PROTOCOL.CHECK_TIME IS '체크시간';
COMMENT ON COLUMN TB_GAME_HISTORY_PROTOCOL.REVIEW_CATEGORY IS '리뷰종류';
COMMENT ON COLUMN TB_GAME_HISTORY_PROTOCOL.REVIEW_TIME IS '리뷰시간';
COMMENT ON COLUMN TB_GAME_HISTORY_PROTOCOL.PROTOCOL_JUDGE IS '판정';
COMMENT ON COLUMN TB_GAME_HISTORY_PROTOCOL.PROTOCOL_RESULT IS '판정결과(퇴장,페널티킥,득점시)';
COMMENT ON COLUMN TB_GAME_HISTORY_PROTOCOL.WRONG_YN IS '오심여부';
COMMENT ON COLUMN TB_GAME_HISTORY_PROTOCOL.GRAY_ZONE_YN IS '애매한상황';
COMMENT ON COLUMN TB_GAME_HISTORY_PROTOCOL.REG_USER IS '등록자';
COMMENT ON COLUMN TB_GAME_HISTORY_PROTOCOL.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_GAME_HISTORY_VOD_THUMBNAIL.GAME_SEQ IS '';
COMMENT ON COLUMN TB_GAME_HISTORY_VOD_THUMBNAIL.GAME_HISTORY_SEQ IS '';
COMMENT ON COLUMN TB_GAME_HISTORY_VOD_THUMBNAIL.VOD_INFO_SEQ IS '';
COMMENT ON COLUMN TB_GAME_HISTORY_VOD_THUMBNAIL.IMG_PATH IS '';
COMMENT ON COLUMN TB_GAME_HISTORY_VOD_THUMBNAIL.IMG_"NAME" IS '';
COMMENT ON COLUMN TB_GAME_HISTORY_WRONG.SEQ IS '번호';
COMMENT ON COLUMN TB_GAME_HISTORY_WRONG.GAME_SEQ IS '게임번호';
COMMENT ON COLUMN TB_GAME_HISTORY_WRONG.GAME_HISTORY_SEQ IS '이벤트번호';
COMMENT ON COLUMN TB_GAME_HISTORY_WRONG.REF_"TYPE" IS '심판구분';
COMMENT ON COLUMN TB_GAME_HISTORY_WRONG.WRONG_CODE IS '오심코드';
COMMENT ON COLUMN TB_GAME_HISTORY_WRONG.MISS_CODE IS '오심코드 구분';
COMMENT ON COLUMN TB_GAME_HISTORY_WRONG.REG_USER IS '등록자';
COMMENT ON COLUMN TB_GAME_HISTORY_WRONG.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_GAME_INFO.SEQ IS '';
COMMENT ON COLUMN TB_GAME_INFO.EVENT_SEQ IS '대회정보SEQ';
COMMENT ON COLUMN TB_GAME_INFO.GAME_ROUND IS '경기라운드';
COMMENT ON COLUMN TB_GAME_INFO.GAME_"NAME" IS '경기명';
COMMENT ON COLUMN TB_GAME_INFO.GAME_DATE IS '경기일';
COMMENT ON COLUMN TB_GAME_INFO.GAME_PLACE IS '경기장소';
COMMENT ON COLUMN TB_GAME_INFO.TEAM1_SEQ IS '경기팀1SEQ';
COMMENT ON COLUMN TB_GAME_INFO.TEAM2_SEQ IS '경기팀2SEQ';
COMMENT ON COLUMN TB_GAME_INFO.TEAM1_SCORE IS '경기팀1최종스코어';
COMMENT ON COLUMN TB_GAME_INFO.TEAM2_SCORE IS '경기팀2최종스코어';
COMMENT ON COLUMN TB_GAME_INFO.LEAGUE_CODE IS '리그종류CODE (GROUP_CODE: LG01)';
COMMENT ON COLUMN TB_GAME_INFO.REFEREE IS '주심';
COMMENT ON COLUMN TB_GAME_INFO.A_REF1 IS '부심1';
COMMENT ON COLUMN TB_GAME_INFO.A_REF2 IS '부심2';
COMMENT ON COLUMN TB_GAME_INFO.FOURTH_REF IS '대기심';
COMMENT ON COLUMN TB_GAME_INFO.VAR IS 'var';
COMMENT ON COLUMN TB_GAME_INFO.AVAR IS 'avar';
COMMENT ON COLUMN TB_GAME_INFO.REPLAY_OP IS 'RO';
COMMENT ON COLUMN TB_GAME_INFO.REPLAY_AS IS 'RA';
COMMENT ON COLUMN TB_GAME_INFO.BROADCASTER IS '방송사';
COMMENT ON COLUMN TB_GAME_INFO.VOD_FIRST_HALF IS 'vod전반전시작시간(초)';
COMMENT ON COLUMN TB_GAME_INFO.VOD_SECOND_HALF IS 'vod후반전시작시간(초)';
COMMENT ON COLUMN TB_GAME_INFO.VOD_OVERTIME_FIRST_HALF IS '';
COMMENT ON COLUMN TB_GAME_INFO.VOD_OVERTIME_SECOND_HALF IS '';
COMMENT ON COLUMN TB_GAME_INFO.VOD_FIRST_END IS '';
COMMENT ON COLUMN TB_GAME_INFO.VOD_SECOND_END IS '';
COMMENT ON COLUMN TB_GAME_INFO.VOD_OVERTIME_FIRST_END IS '';
COMMENT ON COLUMN TB_GAME_INFO.VOD_OVERTIME_SECOND_END IS '';
COMMENT ON COLUMN TB_GAME_INFO.OPEN_YN IS '공개여부';
COMMENT ON COLUMN TB_GAME_INFO.END_YN IS '경기종료여부';
COMMENT ON COLUMN TB_GAME_INFO.REG_USER IS '등록자';
COMMENT ON COLUMN TB_GAME_INFO.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_GAME_INFO.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_GAME_INFO.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_GAME_INFO.CONFIRM_STATE IS '체크리스트 ';
COMMENT ON COLUMN TB_GAME_INFO.SUBMIT_DATE IS 'RA제출시간';
COMMENT ON COLUMN TB_GAME_INFO.CONFIRM_DATE IS 'RO승인시간';
COMMENT ON COLUMN TB_GAME_INFO.SENDER_PWD IS 'Sender 비밀번호';
COMMENT ON COLUMN TB_GAME_INFO.RECEIVER_PWD IS 'Receiver 비밀번호';
COMMENT ON COLUMN TB_GAME_INFO_AVAR.SEQ IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR.SUB_SEQ IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR.VAR_PROTOCOL IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR.ORIGINAL_DECISION IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR.JUDGE_REASON IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR.JUDGE_REVIEW IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR.JUDGE_RESULT IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR.MESSAGE_CODE IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR.MESSAGE_SUB_CODE IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR.USE_YN IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR.CUSER IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR.CDATE IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR.EUSER IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR.EDATE IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_HISTORY.SEQ IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_HISTORY.SUB_SEQ IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_HISTORY.AVAR_"TYPE" IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_HISTORY.CUSER IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_HISTORY.CDATE IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_HISTORY_NEW.SEQ IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_HISTORY_NEW.SUB_SEQ IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_HISTORY_NEW.P_CODE IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_HISTORY_NEW.CUSER IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_HISTORY_NEW.CDATE IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_MESSAGE.CODE IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_MESSAGE.SUB_CODE IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_MESSAGE.MESSAGE1 IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_MESSAGE.MESSAGE2 IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_MESSAGE.MESSAGE3 IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_MESSAGE.USE_YN IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_NEW.SEQ IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_NEW.SUB_SEQ IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_NEW.P1 IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_NEW.P2 IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_NEW.P3 IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_NEW.P4 IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_NEW.MESSAGE_T IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_NEW.MESSAGE_B IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_NEW.USE_YN IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_NEW.CUSER IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_NEW.CDATE IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_NEW.EUSER IS '';
COMMENT ON COLUMN TB_GAME_INFO_AVAR_NEW.EDATE IS '';
COMMENT ON COLUMN TB_LIVE_INFO.SEQ IS '';
COMMENT ON COLUMN TB_LIVE_INFO.GAME_SEQ IS '경기번호';
COMMENT ON COLUMN TB_LIVE_INFO.SUBJECT IS '방송제목';
COMMENT ON COLUMN TB_LIVE_INFO.CONTENTS IS '방송내용';
COMMENT ON COLUMN TB_LIVE_INFO.CHANNEL IS '채널번호';
COMMENT ON COLUMN TB_LIVE_INFO.LIVE_YN IS '방송여부';
COMMENT ON COLUMN TB_LIVE_INFO.OPEN_YN IS '공개여부';
COMMENT ON COLUMN TB_LIVE_INFO.REG_USER IS '등록자';
COMMENT ON COLUMN TB_LIVE_INFO.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_LIVE_INFO.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_LIVE_INFO.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_MENU_ADMIN.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN TB_MENU_ADMIN.MENU_"NAME" IS '메뉴명';
COMMENT ON COLUMN TB_MENU_ADMIN.DEPTH IS '메뉴단계';
COMMENT ON COLUMN TB_MENU_ADMIN.URL IS 'URL';
COMMENT ON COLUMN TB_MENU_ADMIN.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_MENU_ADMIN.REG_USER IS '등록자';
COMMENT ON COLUMN TB_MENU_ADMIN.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_MENU_ADMIN.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_MENU_ADMIN.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_MENU_AUTH.AUTH_CODE IS '권한코드';
COMMENT ON COLUMN TB_MENU_AUTH.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN TB_MENU_AUTH.REG_USER IS '등록자';
COMMENT ON COLUMN TB_MENU_AUTH.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_MENU_AUTH_copy.AUTH_CODE IS '권한코드';
COMMENT ON COLUMN TB_MENU_AUTH_copy.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN TB_MENU_AUTH_copy.REG_USER IS '등록자';
COMMENT ON COLUMN TB_MENU_AUTH_copy.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_MENU_FRONT.MENU_ID IS '메뉴ID';
COMMENT ON COLUMN TB_MENU_FRONT.MENU_"NAME" IS '메뉴명';
COMMENT ON COLUMN TB_MENU_FRONT.DEPTH IS '메뉴단계';
COMMENT ON COLUMN TB_MENU_FRONT.URL IS 'URL';
COMMENT ON COLUMN TB_MENU_FRONT.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_MENU_FRONT.REG_USER IS '등록자';
COMMENT ON COLUMN TB_MENU_FRONT.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_MENU_FRONT.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_MENU_FRONT.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_MENU_INFO.MENU_ID IS '메뉴아이디';
COMMENT ON COLUMN TB_MENU_INFO.MENU_"NAME" IS '메뉴명';
COMMENT ON COLUMN TB_MENU_INFO.MENU_PATH IS '메뉴경로';
COMMENT ON COLUMN TB_MENU_INFO.MENU_UPPER IS '상위메뉴상태여부';
COMMENT ON COLUMN TB_MENU_INFO.MENU_SORT IS '메뉴순서';
COMMENT ON COLUMN TB_MENU_INFO.MEMO IS '메모';
COMMENT ON COLUMN TB_MENU_INFO.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_MENU_INFO.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_MENU_INFO_copy.MENU_ID IS '메뉴아이디';
COMMENT ON COLUMN TB_MENU_INFO_copy.MENU_"NAME" IS '메뉴명';
COMMENT ON COLUMN TB_MENU_INFO_copy.MENU_PATH IS '메뉴경로';
COMMENT ON COLUMN TB_MENU_INFO_copy.MENU_UPPER IS '상위메뉴상태여부';
COMMENT ON COLUMN TB_MENU_INFO_copy.MENU_SORT IS '메뉴순서';
COMMENT ON COLUMN TB_MENU_INFO_copy.MEMO IS '메모';
COMMENT ON COLUMN TB_MENU_INFO_copy.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_MENU_INFO_copy.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_NEW_GAME_CHECK.GAME_SEQ IS 'MAIN_SEQ';
COMMENT ON COLUMN TB_NEW_GAME_CHECK.CHECK_CODE IS '체크목록';
COMMENT ON COLUMN TB_NEW_GAME_CHECK.CHECK_STATE IS '상태';
COMMENT ON COLUMN TB_NEW_GAME_CHECK.CHECK_NOTE IS '비고';
COMMENT ON COLUMN TB_NEW_GAME_CHECK.REG_USER IS '작성자';
COMMENT ON COLUMN TB_NEW_GAME_CHECK.REG_DATE IS '작성일';
COMMENT ON COLUMN TB_PRICE_INFO.SEQ IS '순번';
COMMENT ON COLUMN TB_PRICE_INFO.YEAR IS '년도';
COMMENT ON COLUMN TB_PRICE_INFO.REFEREE_"TYPE" IS '심판구분';
COMMENT ON COLUMN TB_PRICE_INFO.PRICE IS '금액';
COMMENT ON COLUMN TB_RECORD_FILES.SEQ IS '';
COMMENT ON COLUMN TB_RECORD_FILES.GAME_SEQ IS '';
COMMENT ON COLUMN TB_RECORD_FILES.UPLOAD_PATH IS '';
COMMENT ON COLUMN TB_RECORD_FILES.ORIGINAL_FILE_"NAME" IS '';
COMMENT ON COLUMN TB_RECORD_FILES.SAVE_FILE_"NAME" IS '';
COMMENT ON COLUMN TB_RECORD_FILES.FILE_"TYPE" IS '';
COMMENT ON COLUMN TB_RECORD_FILES.FILE_SIZE IS '';
COMMENT ON COLUMN TB_RECORD_FILES.REG_USER IS '';
COMMENT ON COLUMN TB_RECORD_FILES.REG_DATE IS '';
COMMENT ON COLUMN TB_REFEREE_GRADE.GAME_SEQ IS '경기번호';
COMMENT ON COLUMN TB_REFEREE_GRADE.USER_ID IS '유저ID';
COMMENT ON COLUMN TB_REFEREE_GRADE.REF_"TYPE" IS '심판타입';
COMMENT ON COLUMN TB_REFEREE_GRADE.REF_CATEGORY IS '주심,부심1,부심2,대기심구분';
COMMENT ON COLUMN TB_REFEREE_GRADE.GRADE IS '평점';
COMMENT ON COLUMN TB_REFEREE_GRADE.OPTION1 IS '주:경기운영 , 부:파울협력';
COMMENT ON COLUMN TB_REFEREE_GRADE.OPTION2 IS '주: PK , 부:오프사이드';
COMMENT ON COLUMN TB_REFEREE_GRADE.OPTION3 IS '주:체격, 부:시그널';
COMMENT ON COLUMN TB_REFEREE_GRADE.OPTION4 IS '주:파울, 부:스로인';
COMMENT ON COLUMN TB_REFEREE_GRADE.OPTION5 IS '주:경고, 부:스프린터';
COMMENT ON COLUMN TB_REFEREE_GRADE.OPTION6 IS '주:퇴장, 부,코너킥';
COMMENT ON COLUMN TB_REFEREE_GRADE.OPTION7 IS '주:핸드볼';
COMMENT ON COLUMN TB_REFEREE_GRADE.OPTION8 IS '';
COMMENT ON COLUMN TB_REFEREE_GRADE.REG_USER IS '작성자';
COMMENT ON COLUMN TB_REFEREE_GRADE.REG_DATE IS '작성일';
COMMENT ON COLUMN TB_REFEREE_GRADE.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_REFEREE_GRADE.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_REFEREE_GRADE_BAK.GAME_SEQ IS '경기번호';
COMMENT ON COLUMN TB_REFEREE_GRADE_BAK.REFEREE_"NAME" IS '주심이름';
COMMENT ON COLUMN TB_REFEREE_GRADE_BAK.REFEREE_GRADE IS '평점';
COMMENT ON COLUMN TB_REFEREE_GRADE_BAK.REFEREE_CHARGING IS '차징';
COMMENT ON COLUMN TB_REFEREE_GRADE_BAK.REFEREE_PUSHING IS '푸싱';
COMMENT ON COLUMN TB_REFEREE_GRADE_BAK.REFEREE_KICKING IS '킥킹';
COMMENT ON COLUMN TB_REFEREE_GRADE_BAK.REFEREE_JUMPING IS '점핑';
COMMENT ON COLUMN TB_REFEREE_GRADE_BAK.REFEREE_STRIKING IS '스트라이킹';
COMMENT ON COLUMN TB_REFEREE_GRADE_BAK.REFEREE_TACKLE IS '태클';
COMMENT ON COLUMN TB_REFEREE_GRADE_BAK.REFEREE_HOLDING IS '홀딩';
COMMENT ON COLUMN TB_REFEREE_GRADE_BAK.REFEREE_IMPEDING IS '방해';
COMMENT ON COLUMN TB_REFEREE_GRADE_BAK.REFEREE_SPITTING IS '침뱉기';
COMMENT ON COLUMN TB_REFEREE_GRADE_BAK.REFEREE_TRIPPING IS '트래핑';
COMMENT ON COLUMN TB_REFEREE_GRADE_BAK.REFEREE_HANDBALL IS '핸드링';
COMMENT ON COLUMN TB_REFEREE_GRADE_BAK.REG_USER IS '작성자';
COMMENT ON COLUMN TB_REFEREE_GRADE_BAK.REG_DATE IS '작성일';
COMMENT ON COLUMN TB_REFEREE_GRADE_BAK.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_REFEREE_GRADE_BAK.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_REFEREE_INFO_ORIGIN.USER_ID IS '유저ID';
COMMENT ON COLUMN TB_REFEREE_INFO_ORIGIN.ATTACH_PLACE IS '소속협회';
COMMENT ON COLUMN TB_REFEREE_INFO_ORIGIN.CERTNO_YN IS 'FIFA유무';
COMMENT ON COLUMN TB_REFEREE_INFO_ORIGIN.CERTNO_YEAR IS '자격증취득년도';
COMMENT ON COLUMN TB_REFEREE_INFO_ORIGIN.REFEREE_PROIN IS '프로심판 입문년도';
COMMENT ON COLUMN TB_REFEREE_INFO_ORIGIN.REFEREE_WORLDIN IS '국제심판 입문년도';
COMMENT ON COLUMN TB_REFEREE_INFO_ORIGIN.SCHOOL_"NAME"1 IS '학력사항(초등학교)';
COMMENT ON COLUMN TB_REFEREE_INFO_ORIGIN.SCHOOL_"NAME"2 IS '학력사항(중학교)';
COMMENT ON COLUMN TB_REFEREE_INFO_ORIGIN.SCHOOL_"NAME"3 IS '학력사항(고등학교)';
COMMENT ON COLUMN TB_REFEREE_INFO_ORIGIN.SCHOOL_"NAME"4 IS '학력사항(대학교)';
COMMENT ON COLUMN TB_REFEREE_INFO_ORIGIN.SCHOOL_"NAME"5 IS '학력사항(대학원)';
COMMENT ON COLUMN TB_REFEREE_INFO_ORIGIN.REG_USER IS '등록자';
COMMENT ON COLUMN TB_REFEREE_INFO_ORIGIN.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_REFEREE_INFO_ORIGIN.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_REFEREE_INFO_ORIGIN.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.USER_ID IS '유저ID';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.REF_"TYPE" IS '심판구분';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.ACTLEAGUE_"TYPE" IS '심판활동리그';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.FILE_PATH IS '사진경로';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.FILE_"NAME" IS '사진명';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.KR_"NAME" IS '한글성명';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.CN_"NAME" IS '한자성명';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.EN_"NAME" IS '영문성명';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.JUMIN1 IS '주민번호 앞자리';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.JUMIN2 IS '주민번호 뒷자리';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.JOB_"NAME" IS '직업명';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.CORP_"NAME" IS '회사명';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.HOME_ZIPCODE IS '집우편번호';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.HOME_ADDRESS1 IS '집도로명주소';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.HOME_ADDRESS2 IS '집상세주소';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.CORP_ZIPCODE IS '우편주소';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.CORP_ADDRESS1 IS '도로명주소';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.CORP_ADDRESS2 IS '상세주소';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.HPNO IS '연락처';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.HPNO_WIFE IS '배우자연락처';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.EMAIL IS '이메일주소';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.BANK_"NAME" IS '은행명';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.ACCOUNT_NO IS '계좌번호';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.MARRYED_YN IS '결혼여부';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.FAMILY IS '배우자';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.RELIGION IS '종교';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.REG_USER IS '등록자';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_REFEREE_INFO_PERSONAL.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_REFEREE_INFO_PHYSICAL.USER_ID IS '유저ID';
COMMENT ON COLUMN TB_REFEREE_INFO_PHYSICAL.HEIGHT IS '키';
COMMENT ON COLUMN TB_REFEREE_INFO_PHYSICAL.WEIGHT IS '체중';
COMMENT ON COLUMN TB_REFEREE_INFO_PHYSICAL.SIGHT_LEFT IS '시력(좌측)';
COMMENT ON COLUMN TB_REFEREE_INFO_PHYSICAL.SIGHT_RIGHT IS '시력(우측)';
COMMENT ON COLUMN TB_REFEREE_INFO_PHYSICAL.EARPHONE_POS IS '이어폰위치';
COMMENT ON COLUMN TB_REFEREE_INFO_PHYSICAL.WEAR_SIZE IS '의류사이즈';
COMMENT ON COLUMN TB_REFEREE_INFO_PHYSICAL.UNIFORM_SIZE IS '유니폼사이즈';
COMMENT ON COLUMN TB_REFEREE_INFO_PHYSICAL.SHOES_SIZE IS '신발사이즈';
COMMENT ON COLUMN TB_REFEREE_INFO_PHYSICAL.SOCCERSHOES_SIZE IS '축구화사이즈';
COMMENT ON COLUMN TB_REFEREE_INFO_PHYSICAL.MILITARY_"TYPE" IS '병역';
COMMENT ON COLUMN TB_REFEREE_INFO_PHYSICAL.REG_USER IS '등록자';
COMMENT ON COLUMN TB_REFEREE_INFO_PHYSICAL.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_REFEREE_INFO_PHYSICAL.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_REFEREE_INFO_PHYSICAL.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.UPLOAD_SEQ IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.UPLOAD_DTL_SEQ IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.GAME_"NAME" IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.SEQ IS 'TB_GAME_INFO.SEQ';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.GAME_DATE IS '날짜';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.GAME_PLACE IS '장소';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.GAME_HA IS 'H/A';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.TEAM_"NAME" IS '팀';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.REFEREE_NO IS '순번';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.REFEREE_"NAME" IS '이름';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.REFEREE_POSITION IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.USER_ID IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.GAME_MM IS '경기시간(분)';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.GAME_SS IS '경기시간(초)';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.PLAY_MM IS '뛴 시간(분)';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.PLAY_SS IS '뛴 시간(초)';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.PLAY_KM IS '뛴거리(km)';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.PLAY_MINUTE_PER_METER IS '분당거리(m/m)';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.PLAY_KM_PER_HOUR IS '최고속도(km/h)';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.SPRINT_COUNT IS '스프린트(횟수)';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.ACTIVE_AREA_PERCENT IS '활동영역(%)';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.Z1 IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.Z2 IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.Z3 IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.Z4 IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.Z5 IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.Z6 IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.Z7 IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.Z8 IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.Z9 IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.Z10 IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.Z11 IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.Z12 IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.Z13 IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.Z14 IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.Z15 IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.STANDING IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.WALKING IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.JOGGING IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.RUNNING IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.HIR IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_DETAIL.SPRINT IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_MASTER.UPLOAD_SEQ IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_MASTER.EXCEL_FILE_"NAME" IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_MASTER.SYSTEM_FILE_PATH IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_MASTER.SYSTEM_FILE_"NAME" IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_MASTER.REG_USER IS '';
COMMENT ON COLUMN TB_REFEREE_UPLOAD_MASTER.REG_DATE IS '';
COMMENT ON COLUMN TB_SURVEY_ANSWER.SEQ IS '순번';
COMMENT ON COLUMN TB_SURVEY_ANSWER.USER_ID IS '작성자ID';
COMMENT ON COLUMN TB_SURVEY_ANSWER.MAIN_SEQ IS '퀴즈번호';
COMMENT ON COLUMN TB_SURVEY_ANSWER.QUESTION_SEQ IS '문제번호';
COMMENT ON COLUMN TB_SURVEY_ANSWER.MULTIPLE_ANSWER IS '객관식답변';
COMMENT ON COLUMN TB_SURVEY_ANSWER.SUBJECTIVE_ANSWER IS '주관식 답변';
COMMENT ON COLUMN TB_SURVEY_ANSWER.ANSWER_DATE IS '답변날짜';
COMMENT ON COLUMN TB_SURVEY_ANSWER.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_SURVEY_ANSWER_BAK.USER_ID IS '작성자ID';
COMMENT ON COLUMN TB_SURVEY_ANSWER_BAK.QUESTION_SEQ IS '문항SEQ';
COMMENT ON COLUMN TB_SURVEY_ANSWER_BAK.QUESTION_DETAIL_SEQ IS '객관식 답(문항상세SEQ)';
COMMENT ON COLUMN TB_SURVEY_ANSWER_BAK.ANSWER_CONTENTS IS '주관식 답변';
COMMENT ON COLUMN TB_SURVEY_MAIN.SEQ IS '';
COMMENT ON COLUMN TB_SURVEY_MAIN.SUBJECT IS '설문제목';
COMMENT ON COLUMN TB_SURVEY_MAIN.OBJECTIVE IS '설문목적';
COMMENT ON COLUMN TB_SURVEY_MAIN.CONTENTS IS '설문내용';
COMMENT ON COLUMN TB_SURVEY_MAIN.TARGET IS '설문대상';
COMMENT ON COLUMN TB_SURVEY_MAIN.START_DATE IS '시작일';
COMMENT ON COLUMN TB_SURVEY_MAIN.END_DATE IS '종료일';
COMMENT ON COLUMN TB_SURVEY_MAIN.OPEN_YN IS '공개여부';
COMMENT ON COLUMN TB_SURVEY_MAIN.BACK_YN IS '뒤로가기여부';
COMMENT ON COLUMN TB_SURVEY_MAIN.REG_USER IS '등록자';
COMMENT ON COLUMN TB_SURVEY_MAIN.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_SURVEY_MAIN.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_SURVEY_MAIN.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_SURVEY_QUESTION.SEQ IS '';
COMMENT ON COLUMN TB_SURVEY_QUESTION.MAIN_SEQ IS '설문메인SEQ';
COMMENT ON COLUMN TB_SURVEY_QUESTION.QUESTION IS '문항제목';
COMMENT ON COLUMN TB_SURVEY_QUESTION.SORT_ORDER IS '순번';
COMMENT ON COLUMN TB_SURVEY_QUESTION.VOD_SEQ IS 'VOD파일번호';
COMMENT ON COLUMN TB_SURVEY_QUESTION."TYPE" IS '유형(단일/다중/주관식) - CODE: ';
COMMENT ON COLUMN TB_SURVEY_QUESTION.REG_USER IS '등록자';
COMMENT ON COLUMN TB_SURVEY_QUESTION.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_SURVEY_QUESTION.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_SURVEY_QUESTION.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_SURVEY_QUESTION_DETAIL.SEQ IS '';
COMMENT ON COLUMN TB_SURVEY_QUESTION_DETAIL.QUESTION_SEQ IS '설문문항SEQ';
COMMENT ON COLUMN TB_SURVEY_QUESTION_DETAIL.CONTENTS IS '객관식 내용(단일선택 및 다중선택)';
COMMENT ON COLUMN TB_SURVEY_QUESTION_DETAIL.ANSWER IS '객관식 정답YN';
COMMENT ON COLUMN TB_SURVEY_QUESTION_FILE.VOD_SEQ IS '영상 SEQ';
COMMENT ON COLUMN TB_SURVEY_QUESTION_FILE.MAIN_SEQ IS '설문지 MAIN_SEQ';
COMMENT ON COLUMN TB_SURVEY_QUESTION_FILE.FILE_PATH IS '파일경로';
COMMENT ON COLUMN TB_SURVEY_QUESTION_FILE.UPLOAD_PATH IS '업로드경로';
COMMENT ON COLUMN TB_SURVEY_QUESTION_FILE.FILE_"NAME" IS '파일명';
COMMENT ON COLUMN TB_SURVEY_QUESTION_FILE.ORIGINAL_FILE_"NAME" IS '원본파일명';
COMMENT ON COLUMN TB_SURVEY_QUESTION_FILE.SIZE IS '파일크기';
COMMENT ON COLUMN TB_SURVEY_QUESTION_FILE.EXTENSION IS '확장자';
COMMENT ON COLUMN TB_SURVEY_QUESTION_FILE.CONTENTS_"TYPE" IS '파일종류';
COMMENT ON COLUMN TB_SURVEY_QUESTION_FILE.REG_USER IS '등록자';
COMMENT ON COLUMN TB_SURVEY_QUESTION_FILE.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_SURVEY_QUESTION_FILE.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_SURVEY_QUESTION_FILE.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_TEAM_INFO.SEQ IS '';
COMMENT ON COLUMN TB_TEAM_INFO.TEAM_"NAME" IS '팀명';
COMMENT ON COLUMN TB_TEAM_INFO.EN_TEAM_"NAME" IS '영문 팀명';
COMMENT ON COLUMN TB_TEAM_INFO.DESCRIPTION IS '설명';
COMMENT ON COLUMN TB_TEAM_INFO.LEAGUE_"TYPE" IS '팀구분 - CODE: ';
COMMENT ON COLUMN TB_TEAM_INFO.KLEAGUE_YN IS '팀구분 - KLEAGUE팀 여부';
COMMENT ON COLUMN TB_TEAM_INFO.STATUS IS '상태 - CODE: ';
COMMENT ON COLUMN TB_TEAM_INFO.STADIUM_"NAME" IS '경기장명';
COMMENT ON COLUMN TB_TEAM_INFO.MANAGER_"NAME" IS '감독명';
COMMENT ON COLUMN TB_TEAM_INFO.FILE_PATH IS '파일경로';
COMMENT ON COLUMN TB_TEAM_INFO.UPLOAD_PATH IS '업로드경로';
COMMENT ON COLUMN TB_TEAM_INFO.FILE_"NAME" IS '파일명';
COMMENT ON COLUMN TB_TEAM_INFO.REG_USER IS '등록자';
COMMENT ON COLUMN TB_TEAM_INFO.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_TEAM_INFO.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_TEAM_INFO.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_USER.USER_ID IS '회원ID';
COMMENT ON COLUMN TB_USER."PASSWORD" IS '비밀번호';
COMMENT ON COLUMN TB_USER."NAME" IS '이름';
COMMENT ON COLUMN TB_USER.PHONE IS '연락처';
COMMENT ON COLUMN TB_USER.EMAIL IS '이메일';
COMMENT ON COLUMN TB_USER."TYPE" IS '회원구분 - CODE: ';
COMMENT ON COLUMN TB_USER.STATUS IS '회원상태 - CODE: ';
COMMENT ON COLUMN TB_USER.PHOTO IS '회원사진';
COMMENT ON COLUMN TB_USER.ETC IS '비고';
COMMENT ON COLUMN TB_USER.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_USER.STOP_YN IS '정지여부';
COMMENT ON COLUMN TB_USER.DELETE_YN IS '삭제여부';
COMMENT ON COLUMN TB_USER.REG_USER IS '등록자';
COMMENT ON COLUMN TB_USER.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_USER.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_USER.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_USER_TEAM_REL.TEAM_SEQ IS '팀정보SEQ';
COMMENT ON COLUMN TB_USER_TEAM_REL.USER_ID IS '회원ID';
COMMENT ON COLUMN TB_VARREPORT_INFO.SEQ IS 'SEQ';
COMMENT ON COLUMN TB_VARREPORT_INFO.GAME_SEQ IS 'GAME SEQ';
COMMENT ON COLUMN TB_VARREPORT_INFO.HALF IS '전/후반';
COMMENT ON COLUMN TB_VARREPORT_INFO.MINUTE1 IS '분';
COMMENT ON COLUMN TB_VARREPORT_INFO.MINUTE2 IS '초';
COMMENT ON COLUMN TB_VARREPORT_INFO.INCIDENT IS 'INCIDENT';
COMMENT ON COLUMN TB_VARREPORT_INFO.INCIDENT_PK IS 'INCIDENT_PK';
COMMENT ON COLUMN TB_VARREPORT_INFO.TEAM IS 'TEAM';
COMMENT ON COLUMN TB_VARREPORT_INFO.TEAM_NO IS 'NO';
COMMENT ON COLUMN TB_VARREPORT_INFO.DECISION_REF IS 'DECISION REF';
COMMENT ON COLUMN TB_VARREPORT_INFO.CARD_REF IS 'CARD REF	';
COMMENT ON COLUMN TB_VARREPORT_INFO.CHECK1 IS 'RESULT';
COMMENT ON COLUMN TB_VARREPORT_INFO.CHECK2 IS 'DURATION';
COMMENT ON COLUMN TB_VARREPORT_INFO.CHECK3 IS 'REF OR VAR';
COMMENT ON COLUMN TB_VARREPORT_INFO.REVIEW1 IS 'STOPPAGE FOR REVIEW';
COMMENT ON COLUMN TB_VARREPORT_INFO.REVIEW2 IS 'RECOMM. DECISION VAR';
COMMENT ON COLUMN TB_VARREPORT_INFO.REVIEW3 IS 'OFR OR VAR';
COMMENT ON COLUMN TB_VARREPORT_INFO.REVIEW4 IS 'RECOMM. CARD VAR';
COMMENT ON COLUMN TB_VARREPORT_INFO.REVIEW5 IS 'RECOMM. OFR';
COMMENT ON COLUMN TB_VARREPORT_INFO.REVIEW6 IS 'DURATION REVIEW+OFR';
COMMENT ON COLUMN TB_VARREPORT_INFO.COMMENTS IS 'COMMENTS';
COMMENT ON COLUMN TB_VARREPORT_INFO.REG_USER IS '작성자';
COMMENT ON COLUMN TB_VARREPORT_INFO.REG_DATE IS '작성일';
COMMENT ON COLUMN TB_VARREPORT_INFO.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_VARREPORT_INFO.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_VAR_CHANNEL.SEQ IS 'SEQ';
COMMENT ON COLUMN TB_VAR_CHANNEL.CH IS '채널';
COMMENT ON COLUMN TB_VAR_CHANNEL.SENDER_PWD IS '송신 암호';
COMMENT ON COLUMN TB_VAR_CHANNEL.RECEIVER_PWD IS '수신';
COMMENT ON COLUMN TB_VAR_CHANNEL.CUR_EVENT IS '현재 체크중인 이벤트';
COMMENT ON COLUMN TB_VAR_CHANNEL.USE_YN IS '채널 사용여부';
COMMENT ON COLUMN TB_VAR_CHANNEL.REG_DATE IS '채널 작성날짜';
COMMENT ON COLUMN TB_VAR_CHANNEL.UDT_DATE IS '채널 수정날짜';
COMMENT ON COLUMN TB_VAR_EVENT.SEQ IS '';
COMMENT ON COLUMN TB_VAR_EVENT.EVE_ORDER1 IS '';
COMMENT ON COLUMN TB_VAR_EVENT.EVE_ORDER2 IS '';
COMMENT ON COLUMN TB_VAR_EVENT.FILE_"NAME" IS '';
COMMENT ON COLUMN TB_VAR_EVENT.FINAL_YN IS '';
COMMENT ON COLUMN TB_VAR_EVENT.OPTION1 IS '';
COMMENT ON COLUMN TB_VOD.SEQ IS '';
COMMENT ON COLUMN TB_VOD.SUBJECT IS '제목';
COMMENT ON COLUMN TB_VOD.CONTENTS IS '내용';
COMMENT ON COLUMN TB_VOD.EVENT_"NAME" IS '대회명 (대회관리 필요??)';
COMMENT ON COLUMN TB_VOD.GAME_"NAME" IS '경기명';
COMMENT ON COLUMN TB_VOD.GAME_DATE IS '경기일';
COMMENT ON COLUMN TB_VOD.GAME_PLACE IS '경기장소';
COMMENT ON COLUMN TB_VOD.THUMBNAIL IS '썸네일이미지';
COMMENT ON COLUMN TB_VOD.VOD_FILE IS 'VOD파일번호';
COMMENT ON COLUMN TB_VOD.OPEN_YN IS '공개여부';
COMMENT ON COLUMN TB_VOD.REG_USER IS '등록자';
COMMENT ON COLUMN TB_VOD.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_VOD.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_VOD.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_VOD_COMMENT.SEQ IS '';
COMMENT ON COLUMN TB_VOD_COMMENT.VOD_SEQ IS 'VOD SEQ';
COMMENT ON COLUMN TB_VOD_COMMENT.USER_ID IS '작성자ID';
COMMENT ON COLUMN TB_VOD_COMMENT.CONTENTS IS '댓글내용';
COMMENT ON COLUMN TB_VOD_COMMENT.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TB_VOD_COMMENT.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_VOD_COMMENT.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_VOD_COMMENT.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_VOD_FILE_INFO.SEQ IS '';
COMMENT ON COLUMN TB_VOD_FILE_INFO.GAME_SEQ IS '파일GROUP번호';
COMMENT ON COLUMN TB_VOD_FILE_INFO.FILE_PATH IS '파일경로';
COMMENT ON COLUMN TB_VOD_FILE_INFO.UPLOAD_PATH IS '업로드경로';
COMMENT ON COLUMN TB_VOD_FILE_INFO.FILE_"NAME" IS '파일명';
COMMENT ON COLUMN TB_VOD_FILE_INFO.ORIGINAL_FILE_"NAME" IS '원본파일명';
COMMENT ON COLUMN TB_VOD_FILE_INFO.SIZE IS '파일크기';
COMMENT ON COLUMN TB_VOD_FILE_INFO.EXTENSION IS '확장자';
COMMENT ON COLUMN TB_VOD_FILE_INFO.CONTENTS_"TYPE" IS '파일종류';
COMMENT ON COLUMN TB_VOD_FILE_INFO.REG_USER IS '등록자';
COMMENT ON COLUMN TB_VOD_FILE_INFO.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_VOD_FILE_INFO.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_VOD_FILE_INFO.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_VOD_FILE_INFO_copy.SEQ IS '';
COMMENT ON COLUMN TB_VOD_FILE_INFO_copy.GAME_SEQ IS '파일GROUP번호';
COMMENT ON COLUMN TB_VOD_FILE_INFO_copy.FILE_PATH IS '파일경로';
COMMENT ON COLUMN TB_VOD_FILE_INFO_copy.UPLOAD_PATH IS '업로드경로';
COMMENT ON COLUMN TB_VOD_FILE_INFO_copy.FILE_"NAME" IS '파일명';
COMMENT ON COLUMN TB_VOD_FILE_INFO_copy.ORIGINAL_FILE_"NAME" IS '원본파일명';
COMMENT ON COLUMN TB_VOD_FILE_INFO_copy.SIZE IS '파일크기';
COMMENT ON COLUMN TB_VOD_FILE_INFO_copy.EXTENSION IS '확장자';
COMMENT ON COLUMN TB_VOD_FILE_INFO_copy.CONTENTS_"TYPE" IS '파일종류';
COMMENT ON COLUMN TB_VOD_FILE_INFO_copy.REG_USER IS '등록자';
COMMENT ON COLUMN TB_VOD_FILE_INFO_copy.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_VOD_FILE_INFO_copy.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_VOD_FILE_INFO_copy.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_VOD_INFO.SEQ IS '';
COMMENT ON COLUMN TB_VOD_INFO.GAME_SEQ IS '경기정보SEQ';
COMMENT ON COLUMN TB_VOD_INFO.VOD_"NAME" IS '영상제목';
COMMENT ON COLUMN TB_VOD_INFO.FILE_"NAME" IS '파일명';
COMMENT ON COLUMN TB_VOD_INFO.INSTANCE_ID IS 'INSTANCE ID';
COMMENT ON COLUMN TB_VOD_INFO.FILE_ID IS '파일ID';
COMMENT ON COLUMN TB_VOD_INFO.CAMERA_CODE IS '카메라코드';
COMMENT ON COLUMN TB_VOD_INFO.OPEN_YN IS '공개여부';
COMMENT ON COLUMN TB_VOD_INFO.REG_USER IS '등록자';
COMMENT ON COLUMN TB_VOD_INFO.REG_DATE IS '등록일';
COMMENT ON COLUMN TB_VOD_INFO.MOD_USER IS '수정자';
COMMENT ON COLUMN TB_VOD_INFO.MOD_DATE IS '수정일';
COMMENT ON COLUMN TB_VOD_INFO.FIRST_TOTAL_SEC IS '전반시작시간(초)';
COMMENT ON COLUMN TB_VOD_INFO.SECOND_TOTAL_SEC IS '후반시작시간(초)';
COMMENT ON COLUMN TB_VOD_INFO.UPLOAD_"TYPE" IS '업로드방식 S:일반, A:아마존';
COMMENT ON COLUMN TB_VOD_"TYPE".VOD_SEQ IS '경기영상SEQ';
COMMENT ON COLUMN TB_VOD_"TYPE"."TYPE"_CODE IS '영상종류CODE (GROUP_CODE: VOD01)';
COMMENT ON COLUMN tm_file.FILE_SEQ IS '파일번호';
COMMENT ON COLUMN tm_file.REAL_FILE_"NAME" IS '파일명';
COMMENT ON COLUMN tm_file.SERVER_FILE_"NAME" IS '서버에저장된파일명';
COMMENT ON COLUMN tm_file.PHYSICAL_PATH IS '파일저장경로';
COMMENT ON COLUMN tm_file.CREATE_DATE IS '생성일시';
COMMENT ON COLUMN tm_file.CONVERT_STATE IS '파일변환상태';
COMMENT ON COLUMN tm_file.STATE IS '파일상태(1:정상,2:삭제)';
COMMENT ON COLUMN tm_file.FOLDER_SEQ IS '폴더번호';
COMMENT ON COLUMN tm_file.FILE_SIZE IS '파일크기';
COMMENT ON COLUMN tm_file.PLAY_TIME IS '재생시간';
COMMENT ON COLUMN tm_file.AUDIO_FORMAT IS '오디오포맷';
COMMENT ON COLUMN tm_file.VIDEO_FORMAT IS '비디오포맷';
COMMENT ON COLUMN tm_file.INSTANCE_SEQ IS '인스턴스번호';
COMMENT ON COLUMN tm_file.AUDIO_CODEC IS '오디오코덱';
COMMENT ON COLUMN tm_file.VIDEO_CODEC IS '비디오코덱';
COMMENT ON COLUMN tm_file.VIDEO_SIZE IS '비디오크기';
COMMENT ON COLUMN tm_file.SMIL_FILE IS '싱크미디어리스트';

