SELECT C.TABLE_NAME, C.TABLE_COMMENT
     , C.COLUMN_NAME, C.COLUMN_COMMENT
     , C.ORDINAL_POSITION AS COL_IDX, C.DATA_TYPE, C.CHARACTER_MAXIMUM_LENGTH AS LEN, C.IS_NULLABLE AS NULL_AT
     , D.CONSTRAINT_NAME AS KEY_NM, D.ORDINAL_POSITION AS KEY_ORD
  FROM (
        SELECT TAB.TABLE_NAME, TAB.TABLE_COMMENT
             , COL.COLUMN_NAME, COL.COLUMN_COMMENT
             , COL.ORDINAL_POSITION, COL.DATA_TYPE, COL.CHARACTER_MAXIMUM_LENGTH, COL.IS_NULLABLE
          FROM INFORMATION_SCHEMA.TABLES TAB
             , INFORMATION_SCHEMA.COLUMNS COL
         WHERE TAB.TABLE_NAME = COL.TABLE_NAME
           AND TAB.TABLE_TYPE = 'BASE TABLE'
           AND TAB.TABLE_SCHEMA = 'KRMS'
           AND COL.TABLE_SCHEMA = 'KRMS'
       ) C
       LEFT OUTER JOIN
       (
        SELECT U.TABLE_NAME, U.COLUMN_NAME, U.CONSTRAINT_NAME, U.ORDINAL_POSITION
          FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE U
             , INFORMATION_SCHEMA.TABLE_CONSTRAINTS T
         WHERE U.TABLE_SCHEMA = 'KRMS'
           AND U.TABLE_SCHEMA = T.TABLE_SCHEMA
           AND U.CONSTRAINT_NAME = T.CONSTRAINT_NAME
           AND U.CONSTRAINT_SCHEMA = T.CONSTRAINT_SCHEMA 
           AND U.CONSTRAINT_CATALOG = T.CONSTRAINT_CATALOG 
           AND U.TABLE_NAME = T.TABLE_NAME 
           AND T.CONSTRAINT_TYPE = 'PRIMARY KEY'
       ) D
    ON C.TABLE_NAME = D.TABLE_NAME
   AND C.COLUMN_NAME = D.COLUMN_NAME
 ORDER BY C.TABLE_NAME, C.ORDINAL_POSITION